crowbartools/Firebot

- .gitignore
- build-notes.txt
- gui/js/settings.js
- lib/login/login.js
- package.json
Added an animation to give some feedback for interaction with the Save / Cancel buttons as well as a trigger to tell if the settingsReset was called by the user with the Cancel button or just by code like in settingsSave().
Changes done in three of these commits should fix #13 and might help with #7 as well as help with the initial build of a clean clone. Just have to add the `npm run rebuild` part into the build instructions.
> Firebotremastered

- gui/css/main.css
- gui/js/settings.js
Added a margin-bottom to fix the overlapping issues with the tips bar. Issue #40
> Added a margin to fix the overlapping issues with the tips bar

- lib/login/login.js
Just thought I'd quickly fire this here to get it out of the way!
Resolves #63
> Allow Auth with Microsoft, Twitter, & Discord

- lib/interactive/chat-connect.js
Changed "You need to to log into the app as a streamer. (chat-connect)" to "You need to log into the app as a streamer. (chat-connect)'"
> Fixed two typos

- gui/js/interactive/interactive-board.js
Take 2: The Fixed Branch Edition
This is a super small update that makes the spinners that appear when you manually trigger a button actually "spin". It utilizes the font awesome `fa-pulse` class which causes the spinner icon to rotate by 8 steps until removed. Completely trivial, but my ocd insisted they moved!
[Font Awesome docs on spinners](http://fontawesome.io/examples/#animated)
Loving the app!
> Tiny spinner update

- gui/js/login.js
- package.json
Sorry for the spacing changes, I use ALT-SHIFT-F sometimes.
> Switch Firebot to electron-oauth2 package 

- gui/index.html
- gui/js/login.js
Getting acquainted with the code and tried to help with a couple tiny little things.
- Fix for #146
- Fix for the case where a streamer or bot might not have an avatar and the container on the login page would become a tiny empty rectangle instead.
~Octanewt
> Download button and keep placeholder image for missing avatars

- gui/index.html
> Added Contributors to the Info page

- gui/js/interactive/controls-editor.js
- gui/js/interactive/handler/mediaHandler.js
- lib/interactive/handlers/mediaProcessor.js
- overlay/js/main.js
Looking into #143, added the fields necessary and saving procedure for
size settings. Overlay gets the value, but I've not finalized the code for
it there yet as I encountered some centering issues when resizing the
image.
I've left the code I've added in the overlay so far, but it's commented out at line 81 in overlay/js/main.js for now.
> Preparations for Image Sizing

- lib/interactive/handlers/customScriptProcessor.js
This passes a modules object containing the request package to custom scripts so they have access to that.
> Pass a modules object to custom scripts.

- gui/js/interactive/controls-editor.js
- lib/interactive/control-router.js
- lib/interactive/effect-runner.js
This allows you to add delays between effects!
I've refactored the control-router code and added a new "effect-runner" class that handles effect execution.
I also took the opportunity to combine logic for the manual vs regular activation of buttons. This removes one of the many Switch statements for buttons...progress!
Initial testing seems to be good, but we will want to verify all effects in regular and manual activation.
> Delay Button Effect

- gui/index.html
- gui/js/interactive/controls-editor.js
This fixes a bug that prevented Custom Script effects to properly save.
(I also corrected the capitalization of my name in the Contributions section)
> Fix Custom Script Save Bug

- .github/issue_template.md
Just added an instruction to share the board with us to make it quicker, one post less back and forth asking them to do so.
> Board shared with devs?

- gui/app/templates/_settings.html
I added tabs to the settings page to try to organize it a bit. There are now tabs for "General", "Interactive", and "Overlay". This should allow us to add even more settings while making it easier for people to find what they're looking for in there.
> Tab the settings page to organize it a bit.

- gui/app/services/boardService.js
- gui/app/services/effectHelperService.js
- gui/app/templates/interactive/effect-options/celebration.html
- gui/app/templates/interactive/effect-options/change-scene.html
- gui/app/templates/interactive/effect-options/cooldown.html
- gui/app/templates/interactive/effect-options/custom-script.html
- gui/app/templates/interactive/effect-options/dice.html
- gui/app/templates/interactive/effect-options/game-control.html
- gui/app/templates/interactive/effect-options/html.html
- gui/js/global.js
- gui/js/interactive/controls-editor.js
- lib/interactive/EffectType.js
- lib/interactive/handlers/customScriptProcessor.js
- main.js
Celebration, cooldown, custom scripts, dice, html button effects added. 
**BREAKING**: Scripts folder moved inside of user settings to better fit in with the overall folder structure.
> New Button Effects

- gui/app/services/boardService.js
- gui/app/services/settingsService.js
Approx halves the amount of reads and rewrites of board files on app startup.
Left some console.log()'s and comments here and there to keep track of my progress. I'll take care of them when the whole process has been completed and implemented.
> lastUpdated now stored in settings as first part of knownBoards

- .vscode/launch.json
- lib/interactive/mixer-interactive.js
- main.js
Correct globalShortcut reference to make debugging smother for VS Code, add debug launch.json
> Corrections for Debugging in VSCode

- gui/app/services/websocketService.js
- gui/app/templates/interactive/effect-options/show-video.html
- lib/interactive/handlers/mediaProcessor.js
- overlay/js/main.js
Needs size controls like regular videos, but that's coming. Just wanted to get this in there for Firebottle to test it out.
> Added options for YouTube IDs for Video overlay

- gui/app/templates/_updates.html
- gui/app/templates/interactive/modals/addBoardModal.html
- gui/app/templates/misc-modals/firstTimeUseModal.html
Just fixing any links that weren't set to open externally.
> fixing links

- gui/app/services/connectionService.js
This should fix #155 and allow all oauth options to successfully authenticate as well as password.
> Oauth Blank MSA login Fixes

- gui/app/services/boardService.js
Helps fix #191 
This will now check the name of the board for periods. If one exists it will abort loading the board and ask the user to change the name.
Also fixed the error log code that was left in board service from the last version. It was just throwing console errors before, and now it's pulling from utility service.
> Error fixes and board name checks

- lib/interactive/handlers/game-controls/emulator.js
- lib/interactive/handlers/game-controls/keytranslator.js
This should fix #191 
- Added a check for the game control modifier array to make sure it exists before trying to loop through it. 
- Fixed KBM translator for number pad keys.
> Game control fix.

- gui/app/services/effectHelperService.js
- gui/app/templates/interactive/effect-options/show-video.html
This automatically calculates 16 by 9 for videos and fills out the opposite size field.
> Calculate 16 by 9 for videos.

- gui/app/services/boardService.js
- gui/app/services/connectionService.js
- gui/app/services/utilityService.js
- main.js
This will stop people from trying to import mixer interactive v1 json.
This also has a super simple error logger, though I'm not sure how useful it will be... Anytime a error is thrown that would trigger the error modal it logs the error to a file and attaches the last selected controls json.
I also opted to start throwing errors for uncaught exceptions. It's ugly, but it'll help us hunt down issues easier.
> v1 json check and error logging

- lib/interactive/handlers/apiProcessor.js
> Switching Cat Facts API

- gui/app/templates/_viewergroups.html
- gui/app/templates/interactive/modals/addBoardModal.html
- lib/interactive/cooldowns.js
Some small touch ups to fix a couple of small issues.
> Perry touchups

- gui/app/services/settingsService.js
- gui/app/templates/_settings.html
Adding area to overlay settings to pull up the modal to get your overlay path easier.
> Overlay filepath in settings area

- gui/app/services/effectHelperService.js
- lib/interactive/handlers/apiProcessor.js
- lib/interactive/handlers/mediaProcessor.js
- resources/overlay/js/handlers/videoHandler.js
Adding additional chrome supported video filetypes according to the chrome documentation. I have not tested all of these file types myself, but technically they should work fine.
https://support.google.com/chromebook/answer/183093?hl=en
Also adding Dad Jokes as an api option.
> More video types and Dad Jokes

- gui/app/directives/effect-option-settings/eosOverlayPosition.js
- gui/app/index.html
- gui/app/services/websocketService.js
- gui/app/templates/interactive/effect-options/show-image.html
- gui/app/templates/interactive/effect-options/show-video.html
- lib/interactive/handlers/mediaProcessor.js
- resources/overlay/js/handlers/imageHandler.js
- resources/overlay/js/handlers/videoHandler.js
- resources/overlay/js/main.js
- resources/overlay/scss/_positioning.scss
This adds the ability to allow the user to set a custom position for Video and Image Effects instead of having to use one of our presets.
> Custom Positioning for Videos and Images

- gui/app/controllers/settingsController.js
- gui/app/index.html
- gui/app/services/listenerService.js
- gui/app/services/settingsService.js
- gui/app/services/utilityService.js
- gui/app/templates/_settings.html
- lib/backupManager.js
- lib/interactive/settings-access.js
- main.js
- package.json
Adding backup routine for manually taking backups plus options to make automatic backups on application exit and/or on updates as well as an option to keep all backups or overwriting the backup file each time.
> Perry backup function

- api/v1/controllers/effectsApiController.js
- api/v1/controllers/groupsApiController.js
- gui/app/index.html
- gui/app/services/groupsService.js
- gui/app/services/notificationService.js
- gui/app/services/soundService.js
- gui/app/templates/chat/_commands.html
- gui/app/templates/interactive/_interactive.html
- gui/app/templates/interactive/modals/addBoardModal.html
- gui/app/templates/misc-modals/firstTimeUseModal.html
- gui/css/Dark.css
- gui/css/Light.css
- gui/scss/core/_global.scss
- lib/common/effect-runner.js
- lib/common/handlers/custom-scripts/customScriptProcessor.js
- lib/common/mixer-chat.js
- lib/common/mixer-interactive.js
- lib/interactive/helpers/sparkExemptManager.js
- lib/resourceTokenManager.js
- package.json
just merging the latest from dev to master
> Dev to master merge

- gui/app/directives/controls/scriptParameterOption.js
Added "password" option to custom script parameter fields.
> Added password to script parameter options

- main.js
I don't need the else, it creates a loop.
> dumb error

- gui/app/controllers/mainController.js
- gui/app/directives/sidebar/navCategory.js
- gui/app/directives/sidebar/navLink.js
- gui/app/directives/sidebar/sidebar.js
- gui/app/index.html
- gui/app/index.js
- gui/app/lang/locale-en.json
- gui/app/templates/interactive/_interactive.html
- package-lock.json
- package.json
Added angular-translate
Moved some strings from sidebar and buttons tab to /gui/app/lang/locale-en.json
Other languages can be sourced via files or via web service using angular-translate-loader-url
Also removed confusing connection tooltip code in sidebar that wasn't used to generate tooltips.
Resolves #545
> Translations Phase 1

- gui/app/controllers/settingsController.js
- lib/backupManager.js
- package-lock.json
- package.json
This fixes the ability to backup and restore with multiple profiles. 
This particular fix backs up all profiles at once in the same backup zip. On restore it will completely wipe all current profiles and restore the backup profiles. It's a "completely restore all profiles to this previous state" function now.
I thought super hard about how to backup individual profiles and restore individual profiles, but could not for the life of me come up with a good way to handle it. As users have the ability to share, move backups between computers, etc.. it makes it extremely complicated to make sure the right profiles are getting restore to the right places.
So, this at least gets backups working again. But we might want to revisit this later after some brainstorming or something.
> Backup Manager Fixes

- .editorconfig
- .gitignore
- .idea/Firebot.iml
- .idea/inspectionProfiles/Project_Default.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
I am adding an editorconfig to catch some eslint stuff on the front end, new files were giving me hassles.  I'm also adding the configuration files and such for WebStorm since we've got access to it now, and updating the gitignore to be more specific about what it should exclude based on their recommendations.  This should keep our configurations in sync so we don't run into issues at some point.
> Editor config and Webstorm IDE additions

- gui/app/services/boardService.js
- lib/common/profile-manager.js
Fixed a couple issues with boards loading with multiprofile
> V5 Button Load Bug Fixes

- backend/common/handlers/fileWriterProcessor.js
- backend/effects/builtin/fileWriter.js
- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/fileLineCount.js
- backend/variables/builtin/readFile.js
Changes:
- new variable to count the number of lines in a file.
- update write file effect to allow deleting specific lines OR everything in the file.
- update read file variable to allow for reading a specific line from the file.
Notes:
- All of these changes filter our blank lines in a file. So, if you have 10 lines, but 5 of them are just empty. Then the line counter will report that there are 5 lines in the file.
> Allow reading and deleting specific lines in files.

- backend/database/currencyDatabase.js
- backend/effects/builtin/currency.js
I think the currency stuff needs a refactor sooner or later, but this seems to get the currency effect working correctly if you hit the same person multiple times.
> V5 currency fixes

- gui/scss/core/_chat.scss
Added Partner and VerifiedPartner roles to the Pro role so they get colored the same in the chat list and not the same color as the streamer account.
> Added more roles to the color list

- .github/workflows/build-draft-release.yml
- backend/common/handlers/chatProcessor.js
- backend/common/mixer-chat.js
- backend/database/userDatabase.js
- backend/live-events/filters/builtin-filter-loader.js
- backend/live-events/filters/builtin/message-type.js
- backend/live-events/filters/builtin/message.js
- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/top-currency.js
- backend/variables/builtin/top-view-time.js
- package.json
> v5.6.2 Release 

- backend/effects/builtin/conditional-effects/conditions/builtin/viewer-roles.js
Implements #724 
This updates the "viewer roles" conditional to allow for a left side value. This would allow people to do things like, "If randomTargetUser is in ROLE, then do conditional". Before the target was always the user pressing the button.
Changes:
- Add firebot roles into the conditional roles.
- Make left side a text field.
- Put fallback in place where if left side is empty, we just use the username of the person interacting with the button. This should cover people using the old version of the conditional.
> Implement firebot roles and allow text on left side of conditional.

- backend/common/mixer-chat.js
Implements: #726 
Changes:
- Only add people to active chatter list if the message is not a whisper.
> Only add to active if not whisper.

- backend/common/channel-access.js
- package-lock.json
> Fix sub badges not showing

- backend/effects/builtInEffectLoader.js
- backend/effects/builtin/stream-game.js
- backend/effects/builtin/stream-title.js
Implements #779 
Changes:
- Add effect to set the stream title.
- Add effect to set the stream game.
Both are just simple text areas where you can use replace vars or type in whatever you want. Then it uses the stream management stuff we already have to set the two things.
> Stream management effects

- backend/effects/builtInEffectLoader.js
- backend/effects/builtin/channelProgression.js
Implements #777 
Changes:
- Adds a "Channel Progression" effect that takes a username and amount of hearts.
User can make the amount of hearts negative to take them away or positive to give them. (Just like the chat command).
> Channel progression effect

- backend/effects/builtInEffectLoader.js
- backend/effects/builtin/activeUserLists.js
- backend/roles/role-managers/active-chatters.js
- backend/roles/role-managers/active-mixplay-users.js
Implements #727 
Changes:
- Adds a new effect that allows people to manually add, remove, or clear active chatter and mixplay user lists.
> Add new active list management effect. Remove unused functions.

- backend/auth/mixer-auth.js
- backend/common/channel-access.js
- backend/live-events/mixer-constellation.js
- backend/restrictions/builtin-restrictions-loader.js
- backend/restrictions/builtin/channelGame.js
- backend/restrictions/builtin/channelViewers.js
- gui/app/directives/controls/effectList.js
- package-lock.json
- package.json
Implements #816, #822, #823.
Changes:
- Channel-access now keeps an always updated model of complete channel data. This is done via constellation events being merged into the model.
- Many channel-access functions that used to make api calls, now check against the new model.
- Reorganized mixer-constellation so that subscribe events are separated into different functions.
- Implement game title restriction.
- Implement viewer count restriction.
> New restrictions, constellation organization, channel-access updates.

- backend/common/custom-variable-manager.js
- backend/live-events/builtin/firebotEventSource.js
- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/custom-variable-expired-data.js
- backend/variables/builtin/custom-variable-expired-name.js
- backend/variables/builtin/custom-variable-set-data.js
- backend/variables/builtin/custom-variable-set-name.js
Adding events for Custom Variable Creation and Expiration.
> Custom Variable Creation and Expiration event

- gui/app/directives/restrictions/restrictionItem.js
- gui/app/directives/restrictions/restrictionsSection.js
Implements part of #684 
I've asked for more information on the quotes database fix. But, going to go ahead and open a PR so this doesnt get left behind in the next update. I'll just update this PR if more changes get requested.
> #684 accessibility on restriction menus 

- backend/games/builtin-game-loader.js
- backend/games/builtin/bid/bid-command.js
- backend/games/builtin/bid/bid.js
Implements a bid game.
Changes:
This puts a bidding game in place so that people can run auctions.
!bid start XX - start the bidding
!bid stop - manually stop the bidding and pick a winner
!bid XX - try for a new high bid.
> Implement bidding game.

- backend/integrations/IntegrationManager.js
#834 
Changes:
- Disconnect integration before unlinking.
> Disconnect integration while unlinking 

- backend/variables/builtin/follow-count.js
Related issue/feature request: https://github.com/crowbartools/Firebot/issues/1045
> Update the followCount variable to also accept other usernames

- backend/common/account-access.js
> Fix typos in the account access file

- backend/database/currencyDatabase.js
- backend/effects/builtin/currency.js
> Implement "All Viewers" option for Update Currency effect

- backend/chat/twitch-chat.js
- backend/effects/builtInEffectLoader.js
- backend/effects/builtin/update-vip-role.js
Adds an effect with which you can add or remove VIP badges, similar to mod/unmod. Useful for streamers that have the VIP badge as a channel point redemption or as a subscriber perk.
n/a
> Add an effect for adding and removing VIP badges

- backend/variables/builtin/text-replace.js
Adds flag support for text replace when using regular expressions.
Add regex flags support to $textReplace https://github.com/crowbartools/Firebot/issues/1057
> Add flag support for regex text replace

- backend/common/connection-manager.js
- backend/effects/builtin/toggleConnection.js
- backend/integrations/IntegrationManager.js
- gui/app/services/connectionService.js
Updates the Toggle Connection effect to be able to toggle all services (Twitch + any linked integrations)
Added the ability to choose the connection action: Connect, Disconnect, Toggle
#1085
Tested this extensively on my local, testing all the new options and also testing a Toggle Connection effect created on a previous version
> Add all services to Toggle Connection effect #1085

- backend/database/currencyDatabase.js
Adds a function `getCurrencyByName` to the currency database.
#1093 
The implementation is a mix of `getCurrencyById` and `getCounterByName` from `counter-manager.js` and should therefore just work in the same way.
n/a
> CurrencyDatabase: Get Currency By Name

- backend/chat/chat-listeners/twitch-chat-listeners.js
- backend/events/builtin/twitchEventSource.js
- backend/events/twitch-events/gift-sub.js
- backend/twitch-api/pubsub/pubsub-client.js
- backend/variables/builtin/gift-sub-type.js
- backend/variables/builtin/sub-type.js
This adds gift subs to the pubsub listener and removes them from the chat listener.
Preparation for https://github.com/crowbartools/Firebot/issues/1087 and https://github.com/crowbartools/Firebot/issues/1086
> Add gift subs to the pubsub listener

- backend/events/builtin/twitchEventSource.js
- backend/events/twitch-events/sub.js
- backend/variables/builtin/sub-type.js
This moves the sub type information to the variable that uses it, since it was the only place where the sub type gets requested.
I manually tested the variable input.
> Move sub type functionality to the sub type variable

- backend/events/filters/builtin-filter-loader.js
- backend/events/filters/builtin/gift-duration.js
- backend/events/filters/builtin/is-anonymous.js
- backend/events/twitch-events/gift-sub.js
- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/gift-duration.js
This adds support for anonymous gift subs (not community gift subs) and multimonth gift subs. Both have a filter, and I also added a variable for the multimonth gift subs.
Anonymous filter: https://github.com/crowbartools/Firebot/issues/1086
Multimonth gift subs: https://github.com/crowbartools/Firebot/issues/1087
Can't test the actual data, but I tested with manual input.
> Multimonth and anonymous giftsubs

- backend/chat/commands/builtin/quotes.js
- gui/app/directives/modals/quotes/addOrEditQuoteModal.js
Allow users to save empty dates on quotes, sets empty date to [No Date]
#755
> Allow users to save empty dates on quotes

- gui/app/controllers/channel-rewards.controller.js
Add channel point cost to the main table
#1203
> Add channel point cost to the main table

- backend/events/EventManager.js
- gui/app/controllers/events.controller.js
- gui/app/directives/modals/events/simulateGroupEventsModal.js
- gui/app/index.html
- gui/app/templates/live-events/_events.html
Implement event simulation
#1090 
Manually tested with @ebiggz
> Implement event simulation

- backend/chat/chat-listeners/twitch-chat-listeners.js
- gui/app/services/chat-messages.service.js
> Delete timeout ban messages

- backend/events/events-router.js
- gui/app/directives/modals/events/addOrEditEventModal.js
> implement custom cooldowns for events

- backend/chat/commands/builtin/quotes.js
> add ability to have quotes read via TTS

- backend/variables/builtin/regexExec.js
- backend/variables/builtin/regexTest.js
Fixes the regexEcex.js and regexTest.js having their file names flipped.
N/A
> Fix the regexEcex.js and regexTest.js having their file names flipped

- backend/integrations/builtin/aws/aws.js
- backend/integrations/builtin/aws/text-to-speech-polly-effect.js
- backend/integrations/integrationLoader.js
- package-lock.json
- package.json
Added support to use Amazon's Deep Machine Learning Speech Synthesis engine for Text-To-Speech.
As this engine generates MP3 files, options are very similar to the "Play Sound" effect.
Effect supports all AWS Polly voices, both in pure text and SSML format (proper SSML usage with variables would require #1281 to be merged as well).
* Added an AWS (Amazon Web Services) integration within the integration settings.
* Added an [AWS Polly](https://aws.amazon.com/polly/) Text-to-Speech effect.
No applicable issue, this is a self-implemented feature request.
Tested all the various options offered, as well as the failure scenarios (invalid AWS credentials, invalid SSML markup, etc.)
**Note:** Sorry for the washed out colors; Electron and HDR doesn't mix when taking screenshots.
> feat: added AWS Polly (Text-to-Speech) support

- gui/app/services/preset-effect-lists.service.js
- gui/app/templates/_effects.html
This adds a test button to the preset effect lists tab.
n/a
Tested multiple effects with the button.
> Add a test button for the preset effect lists

- gui/app/index.html
Removed an extra character from index.html (**beloew** --> **below**)
No issues found regarding this
No testing done
> Fixes typo on overlay info

- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/sub-points.js
This adds a variable to display the amount of sub points a streamer has.
https://github.com/crowbartools/Firebot/issues/1290
Tested if the sub point amount is correct with a chat alert.
> Add a variable to show the sub points of the streamer

- .github/workflows/project-automation.yml
I opened a Bugs project board to have a bit of an overview of the amount of bugs that are reported. I added a step to add cards with the Bug label to the Bugs board.
> Add issues with the bug label to the bug project board

- backend/effects/builtin/run-program.js
Adjusted the logic of Run Program effect to handle the following cases:
- When executing a shell script (`.bat`, `.cmd`), spaces are now supported.
- Arguments are properly split taking into account quoted arguments, making using arguments with spaces possible
- The Current Working Directory (`cwd`) is set to the dirname of the script/program.
#1310
Testing each of the scenarios above with batch files and with normal `.exe` (`shell: true/false`).
> fix: run-program effect parsing issues (#1310)

- backend/chat/moderation/chat-moderation-manager.js
- backend/chat/moderation/moderation-service.js
- gui/app/directives/modals/misc/editBannedWordsModal.js
- gui/app/services/chat-moderation.service.js
- package-lock.json
This adds regex support in the banned words list.
https://github.com/crowbartools/Firebot/issues/1259
Tested several regex strings, also checked if a regex works regardless of forward slashes. Checked if the regular banned words still work, and if the UI works properly when a lot of regex strings and words are added.
> Banned words regex support

- backend/chat/commands/commandHandler.js
- gui/app/directives/controls/editable-tags.js
- gui/app/directives/modals/commands/addOrEditCustomCommand/addOrEditCustomCommandModal.html
- gui/app/directives/modals/commands/addOrEditCustomCommand/addOrEditCustomCommandModal.js
- gui/app/directives/sidebar/sidebar.js
- gui/app/index.html
- gui/scss/core/_global.scss
Implements command trigger aliases. Allows you define multiple triggers for one command.
#1129 
Tested on new commands and commands created before update. Tested to make sure all aliases work and that $commandTrigger displays the correct trigger based on what was actually matched
> Implement command trigger aliases

- backend/events/twitch-events/gift-sub.js
- backend/twitch-api/pubsub/pubsub-client.js
- package-lock.json
- package.json
This updates the pubsub client package to fix a connection bug. It also removes workarounds for subscription info since the package now supports that properly.
https://github.com/crowbartools/Firebot/issues/1350
> Update pubsub package

- backend/chat/moderation/chat-moderation-manager.js
- backend/chat/moderation/moderation-service.js
- backend/chat/moderation/raid-message-checker.js
- backend/chat/moderation/url-permit-command.js
- gui/app/services/chat-moderation.service.js
This adds emote limit and url moderation to the moderation service. This also fixes a bug where banned regexes couldn't be removed.
Tested if all mod tools work as intended, with several combinations and settings.
> Moderation worker refactor

- backend/auth/twitch-auth.js
- backend/chat/moderation/raid-message-checker.js
- backend/chat/twitch-chat.js
- backend/common/user-access.js
- backend/twitch-api/resource/users.js
- gui/app/directives/chat/chat-autocomplete-menu.component.js
- gui/app/directives/chat/feed items/chat-message.js
- gui/app/directives/modals/viewers/viewerDetailsModal.js
- gui/app/services/viewers.service.js
Adds block options to the viewer detail modal and the chat feed (both action menu and chat command).
Tested all block options, and checked if the block feature in spam raid protection still works correctly.
> Block viewer UI

- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/account-creation-date.js
Adds a variable to display the creation date of a Twitch account.
https://github.com/crowbartools/Firebot/issues/1335
Tested all available options for the variable and the default one.
> Account creation date variable

- backend/chat/moderation/chat-moderation-manager.js
- backend/effects/builtin/run-command.js
- backend/integrations/builtin/discord/discord-embed-builder.js
- backend/restrictions/builtin/channelGame.js
- gui/app/directives/chat/chat-autocomplete-menu.component.js
- gui/app/services/chat-moderation.service.js
- package.json
Re-implements bug fixes that were rolled back.
No new functionality added
> V5 rolledback bugfixes

- .github/workflows/build-draft-release.yml
- grunt/pack.js
- package-lock.json
Updates various configs to use node v14, and electron v12 when building
> Fix github action builds

- package.json
> Release v5.47.3 (!commands fix)

- backend/chat/chat-helpers.js
- backend/cloud-sync/cloud-sync.js
- backend/common/custom-variable-manager.js
- package.json
- Rolls codebase back to v5.42.2
- Fixes: !commands
- Adds: `CustomVariableManager.getAllVariables()`
> Rollback + Minor fixes

- backend/common/custom-variable-manager.js
Fix using `defaultValue` in `$customVariable`
#1470
Tested locally with both `$customVariable[name]` and `$customVariable[name, null, "default value"]`
> Fix using defaultValue in $customVariable

- backend/database/userDatabase.js
- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/top-metadata-user.js
- backend/variables/builtin/top-metadata.js
Paired programming with @ebiggz
> Metadata vars

- backend/events/builtin/twitchEventSource.js
- backend/events/filters/builtin/is-anonymous.js
- backend/events/twitch-events/gift-sub.js
- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/gift-receivers.js
This adds gift receiver information to the Community Sub Gift event, and a variable to access that information (username and sub months). It also adds a filter to check if a community sub gift is anonymous.
https://github.com/crowbartools/Firebot/issues/1113
I tested this by manually putting 1 community sub gift trigger and 5 regular sub triggers in an effect's code that I then ran.
> Gift sub receivers for the Community Gift Sub event

- backend/currency/currencyManager.js
Fixes offline payouts that occurred when the offline setting is not enabled.
Tested if offline payouts get processed when the setting is enabled, and if they don't get processed when the setting is disabled.
> Fix a bug that causes currency to be paid out when it shouldn't

- gui/app/controllers/chat-messages.controller.js
- gui/app/directives/controls/column-resizer.js
- gui/app/index.html
- gui/app/services/settings.service.js
- gui/app/templates/chat/_chat-messages.html
- gui/scss/core/_chat.scss
- gui/scss/core/_global.scss
This adds resize handles between the dashboard columns, to be able to resize the columns to preferred sizes. 
https://github.com/crowbartools/Firebot/issues/1458
Tested if the widths adjust properly, if the settings save correctly and if all existing elements keep working as expected as well.
https://user-images.githubusercontent.com/72231755/151804986-8573db9b-54ef-4dad-87c6-9838fc4fa98f.mp4
> Add the option to resize columns on the dashboard tab

- .github/workflows/build-draft-release.yml
See: https://github.com/actions/virtual-environments/issues/4856
> Fix the draft release build workflow

- backend/integrations/builtin/discord/discord-embed-builder.js
- backend/integrations/builtin/discord/send-discord-message-effect.js
Added a field for Embed URL to make the title clickable.
#1636
Tested with messages both with and without URL entered to see that both works as expected.
> Add URL field for clickable embeds title #1636

- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/custom-variable-keys.js
This adds a $customVarialbeKeys[variableName] variable that extracts the array of keys of a custom variable. 
This is a resubmit of PR #1637 with fixed issues and onto the correct branch. 
Per the comment about formatting, I couldn't find any line-feed issue in my commits. So hopefully it's fine. I fixed the tabs. 
#1618
Created a custom command to create custom variables and output the result of the custom variables keys. 
Also successfully tried to loop over the resulting array of keys.
> #1618 add $customVarialbeKeys variable

- backend/chat/commands/commandHandler.js
This updates commands so that the cooldown status of the command is checked before the restrictions. Our currency effect has an auto deduct function, and people were passing the restriction and paying the cost, then afterwards they would find out the command was still on cooldown.
The cooldown ultimately overrides all restrictions anyway, so we might as well check it first. I can't think of any situation where this might cause issues with other effects.
#1733 
- Create a command with a currency restriction, auto deduct on, and a cooldown.
- Run the command once and make sure currency is deducted.
- Run the command a second time, while cooldown is still active, and make sure currency is not deducted and you get the cool down message.
N/A
> fix(chat): :bug: Check for command cooldown before restrictions.

- backend/chat/commands/commandHandler.js
Refactor command processing so that subcommand triggers can be fired from anywhere, not just chat messages.
#1752
Ran several commands with various subcommands, some with none, some with/without fallback triggers, ran some using the **Run Command** effect, ran some via the internal REST API. Everything worked as expected.
N/A
> feat: subcommands can now trigger from anywhere

- backend/effects/builtin/random-effect.js
Fixes the Random Effect effect not honoring enabled/disabled state.
Ref: #1766
> Fix: Random Effect not honoring enabled state

- backend/effects/builtin/sequential-effect.js
Applies a similar fix from #1767 to Sequential Effect
> fix: Sequential Effect not honoring disabled state

- backend/variables/builtin/sub-type.js
Update description for `$subType` variable to be more clear about output.
#1786 
N/A
N/A
> fix: $subtype clarification

- backend/effects/builtin/sequential-effect.js
Fixes issue with Sequential Effect active effect filtering
N/A
Verified that Sequential Effects are once again working
N/A
> fix: Sequential Effect active filter

- backend/app-management/electron/window-management.js
- gui/app/directives/modals/misc/aboutModal.js
Adds several options to the **Help** menu and revamps the **About Firebot** dialog box.
N/A
Verified all links in Help menu and About Firebot dialog open to the correct locations.
> feat: updated Help menu/About dialog

- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/file-exists.js
Add new `$fileExists` variable. Returns `'true'` if the file exists, otherwise returns `'false'`.
N/A
Verified a file that exists returns `true` and a file that does not exist returns `false`.
N/A
> feat: $fileExists variable

- package.json
- src/gui/app/index.js
- src/server/http-server-manager.js
Updates the electron run path (fixes titlebar version string in dev), including overlay cwd fix, and enables the titlebar icon
N/A
Verified titlebar version is correct in dev, overlay and icon work in both dev and packaged.
N/A
> fix: electron run path, overlay cwd, titlebar icon

- src/backend/common/data-access.js
Fixes data access/resource copying in dev environment
N/A
Verified resources copied without error in dev environment
N/A
> fix: data access path joining in dev

- src/gui/app/services/notification.service.js
Updates the external notifications URL to the new branch
N/A
N/A
N/A
> chore: updated external notifications URL

- backend/chat/third-party/ffz.js
Better FFZ failure handling
N/A
Verified chat connects in event of FFZ failure
N/A
> fix: better FFZ failure handling

- src/backend/chat/third-party/7tv.js
- src/backend/chat/third-party/bttv.js
- src/backend/chat/third-party/ffz.js
Better handle issues with 3rd party emote services
N/A
Verified chat still works when emote services are down
N/A
> fix: third party emote bad response handling

- src/backend/variables/builtin-variable-loader.js
- src/backend/variables/builtin/number-pad.js
- src/backend/variables/builtin/number-round.js
Adds the new `$padNumber` variable and updates `$round` to support decimal places.
N/A
Verified variables work as intended
N/A
> feat: $round to decimal places, add $padNumber

- src/backend/chat/chat-listeners/active-user-handler.js
- src/backend/chat/twitch-chat.js
- src/backend/database/userDatabase.js
- src/backend/twitch-api/chatter-poll.js
- src/backend/variables/builtin/random-viewer.js
Fixes issues with initial viewer population and `$randomViewer` variable
#1901
Verified user list still populates and polls, `$randomViewer` now works
N/A
> fix: viewer initial populate/update, $randomViewer

- package-lock.json
- package.json
- src/backend/integrations/builtin/obs/effects/toggle-obs-source-visibility.ts
- src/backend/integrations/builtin/obs/obs-remote.ts
Adds support for group sub-sources in OBS integration
#1927
Verified that both grouped and non-grouped sources could have visibility set
N/A
> feat: OBS group source support

- src/backend/integrations/builtin/obs/communicator.ts
- src/backend/integrations/builtin/obs/effects/set-obs-source-text.ts
- src/backend/integrations/builtin/obs/obs-integration.ts
- src/backend/integrations/builtin/obs/obs-remote.ts
Add new **Set OBS Source Text** effect
#1928
Verified OBS text source text could be set both statically or from file
> feat: edit OBS text source (#1928)

- src/backend/channel-rewards/channel-reward-manager.js
- src/backend/chat/twitch-commands/channel-handlers.ts
- src/backend/chat/twitch-commands/chat-handlers.ts
- src/backend/chat/twitch-commands/moderation-handlers.ts
- src/backend/chat/twitch-slash-command-handler.ts
- src/backend/twitch-api/resource/bits.ts
- src/backend/twitch-api/resource/categories.ts
- src/backend/twitch-api/resource/channels.js
- src/backend/twitch-api/resource/chat.ts
- src/backend/twitch-api/resource/moderation.ts
- src/backend/twitch-api/resource/whispers.ts
- src/server/api/v1/controllers/countersApiController.ts
- src/server/api/v1/controllers/customRolesApiController.ts
- src/server/api/v1/controllers/timersApiController.ts
Cleanup of TS `requires` statements to become `imports`, update `exports` declarations, and a couple of minor typing fixes.
N/A
Verified build
N/A
> chore: TS include/export cleanup, minor type fixes

- src/gui/app/directives/chat/chat-autocomplete-menu.component.js
Adds /raid to the chat autocomplete 
Adds /unraid to the chat autocomplete 
#2002
> feat: Add Raid/UnRaid to autocomplete (#2002)

- src/backend/variables/builtin-variable-loader.js
- src/backend/variables/builtin/chat-mode-state.ts
Adds `$chatModeState` variable to indicate if a chat mode was either enabled or disabled
N/A
Verified that the variable changes based on whether a chat mode was disabled or enabled
N/A
> feat: $chatModeState

- src/backend/effects/effectManager.d.ts
- src/backend/effects/models/effect-models.ts
- src/backend/integrations/builtin/obs/effects/change-scene-collection.ts
- src/backend/integrations/builtin/obs/effects/change-scene-effect-type.ts
- src/backend/integrations/builtin/obs/effects/send-raw-obs-websocket-request.ts
- src/backend/integrations/builtin/obs/effects/set-obs-browser-source-url.ts
- src/backend/integrations/builtin/obs/effects/set-obs-source-text.ts
- src/backend/integrations/builtin/obs/effects/start-stream.ts
- src/backend/integrations/builtin/obs/effects/start-virtual-cam.ts
- src/backend/integrations/builtin/obs/effects/stop-stream.ts
- src/backend/integrations/builtin/obs/effects/stop-virtual-cam.ts
- src/backend/integrations/builtin/obs/effects/toggle-obs-source-filter.ts
- src/backend/integrations/builtin/obs/effects/toggle-obs-source-muted.ts
- src/backend/integrations/builtin/obs/effects/toggle-obs-source-visibility.ts
- src/backend/integrations/builtin/obs/obs-integration.ts
- src/backend/integrations/builtin/obs/obs-remote.ts
Adds a new **Send Raw OBS WebSocket Request** effect, similar to the **HTTP Request** effect.
N/A
Verified effect works
> feat: raw OBS WebSocket request effect

- src/backend/chat/commands/commandHandler.js
This is to try to fix the "Is Active" of bug #2012 
I have been struggling with a better solution that takes in account both "system" and "custom" sub command activation.  
#2012 
i have ran this for a week with no adverse effects but i'm sure something is not correct and can not for the life me see what? 
i would like a code review and am expecting to have to change it.
> Fix: 2012 An attempt to fix sub command activation

- src/backend/effects/builtin-effect-loader.js
- src/backend/effects/builtin/create-stream-marker.ts
- src/backend/effects/builtin/raid.ts
Adds a new **Raid/Unraid Twitch Channel** effect.
N/A
Verified effect both starts and cancels raids
> feat: Raid/Unraid Effect

- src/backend/effects/builtin-effect-loader.js
- src/backend/effects/builtin/set-chat-mode.ts
Adds a new **Set Chat Mode** effect.
N/A
Verified chat modes and durations/delays were set
> feat: Set Chat Mode effect

- src/backend/integrations/builtin/obs/communicator.ts
- src/backend/integrations/builtin/obs/effects/set-obs-color-source-color.ts
- src/backend/integrations/builtin/obs/effects/set-obs-image-source-file.ts
- src/backend/integrations/builtin/obs/effects/set-obs-media-source-file.ts
- src/backend/integrations/builtin/obs/obs-integration.ts
- src/backend/integrations/builtin/obs/obs-remote.ts
Adds the following new effects:
- **Set OBS Color Source Color**
- **Set OBS Image Source File**
- **Set OBS Media Source File**
N/A
Verified all effects work as intended
> feat: OBS Color, Image, and Media source effects

- src/backend/chat/chat-listeners/twitch-chat-listeners.js
- src/backend/events/twitch-events/viewer-arrived.js
- src/backend/events/twitch-events/viewer-arrived.ts
- src/backend/variables/builtin/chat-message.js
Adds support for the `$chatMessage` variable to the Viewer Arrived event.
N/A
Validated that chat message is available and does not duplicate event with different messages
N/A
> feat: add $chatMessage to Viewer Arrived event

- src/backend/effects/builtin/cooldown-command.js
removed the Plural of Cooldown 
#2163
have tested with both command and subcommands
> fix: #2163 cooldown effect

- src/backend/variables/builtin/array-element.js
This updates $arrayElement to return as a json string instead of [object Object]
#2169 
I've been stress testing this change for a few hours now and have not had any issues with it.
> Update $arrayElement to return as string

- src/gui/app/directives/modals/integrations/addOrEditDiscordWebhookModal.js
> Fix typo in discord description text

- src/backend/integrations/builtin/obs/effects/change-scene-effect-type.ts
Fix the dropdown select for OBS Switch Scene
#2248 
Ensured the effect now functions as expected, and ensured other effects function as expected as well
> fix: OBS Switch Scene Effect

- src/backend/chat/third-party/7tv.ts
Updates 7tv API to fix retrieving emotes
#2265
Verified global emotes loaded
N/A
> fix: 7tv API changes (#2265)

- src/backend/integrations/builtin/obs/effects/take-obs-source-screenshot.ts
- Enables taking OBS Screenshot of the currently active Scene.
- Fixes the image format dropdown to show the selected type.
#2291
Ensured that both normally selecting a source/scene and using the active scene work. If there's no connection to OBS, it'll silently fail.
> feat: Screenshot currently active OBS Scene

- src/backend/common/handlers/createClipProcessor.js
- src/backend/common/screenshot-helpers.ts
- src/backend/effects/builtin/clips.js
- src/backend/effects/builtin/take-screenshot.js
- src/backend/integrations/builtin/discord/discord-embed-builder.js
- src/backend/integrations/builtin/discord/send-discord-message-effect.js
- src/backend/integrations/builtin/obs/effects/take-obs-source-screenshot.ts
- src/gui/app/directives/controls/screenshot-effect-options.js
- src/gui/app/directives/controls/specialized/discord-webhook-message.js
- src/types/discord.d.ts
- Set Embed Color on Twitch Clip
- Custom Embeds and messages on Screenshot, OBS Screenshot
- Embed Colors on Screenshot, OBS Screenshot, Send Discord Message
- Effect Output `screenshotDataUrl` on Screenshot, OBS Screenshot
Manual regression testing showed no issues using old effects on the patch.
Testing of "Send Discord Effect - Channel Details" embed TBD, requires a streamer.
Ensured effects properly warn when contitions aren't met
Ensured that invalid colors will default to the color defined in code prior to changes
Ensured messages will post with the proper settings
> Discord Refactor

- src/backend/effects/builtin/run-program.js
Added the stdout to a output `programResponse` so other effects can use the response from the program 
- #1176
- Calling own CLI tool for output and used a Custom Variable to set it
- Validated the text in Custom Variable Inspector was updated to expected output from own CLI tool.
> #1176 Add Read output from RunProgram Effect

- src/backend/app-management/electron/events/when-ready.js
- src/backend/notifications/notification-manager.ts
- src/gui/app/app-main.js
- src/gui/app/directives/controls/notificationCenter.js
- src/gui/app/services/notification.service.js
Refactored Firebot notification logic, moved to backend
N/A
Verified external notifications trigger only once
N/A
> chore(notifications): move notification logic to backend

- src/backend/variables/builtin/twitch/subs/sub-users.ts
added displayname to the variable output
#2379
ran an existing effect with no change
ran a new chat effect with the variable and it shows the new display name
{"username":"c_k_y","displayname":"C_K_Y","tier":"3000","isGift":false}
> feat: Add displayname to subNames

- src/backend/effects/builtin/conditional-effects/conditional-effects.js
Fix Effect Outputs used in ifs (Conditional Effect)
#2385
Ensured that effect outputs now work as expected in the conditional effect
> fix(effects): conditional effect conditions now read effect outputs

- src/backend/import/setups/setup-importer.js
- src/backend/quick-actions/quick-action-manager.js
- src/gui/app/directives/chat/quick-actions/quick-actions.js
- src/gui/app/directives/modals/chat/add-or-edit-custom-quick-action-modal.js
Fix import setup not adding quick actions to sorting settings
#2375 
Ensured that sort actions imported through setups are properly added to the settings, and no more errors are produced by the application.
> fix(setups): fix quick actions in setups causing the app to break.

- src/backend/app-management/electron/events/when-ready.js
- src/backend/chat/commands/builtin/quotes.ts
- src/backend/chat/commands/chat-command-handler.ts
- src/backend/chat/third-party/bttv.ts
- src/backend/currency/currency-manager.ts
- src/backend/twitch-api/resource/chat.ts
- src/backend/variables/builtin/misc/quote-as-object.ts
- src/backend/variables/builtin/misc/quote-as-raw-object.ts
- src/backend/variables/builtin/misc/quote.ts
- src/gui/app/directives/controls/specialized/gift-receivers-list.js
- src/gui/app/services/connection.service.js
added missing letters from words 
mostly logging and chat messages 
1 UI change had a missing H
> chore: typos

- src/backend/import/setups/setup-importer.js
- src/backend/quick-actions/quick-action-manager.js
- src/gui/app/directives/chat/quick-actions/quick-actions.js
Fix a regression with adding quick actions
Ensured that adding quick actions through the UI and setups, and removing them through UI and Setups work properly.
> fix(quick actions): fix adding quick actions breaking

- src/backend/quick-actions/quick-action-manager.js
Fixes an issue in quick actions where renaming a quick action does a backend update, but not a frontend update, instead showing an error.
#2419
Ensured quick actions can be created, renamed, saved, triggered and deleted.
> fix(quick actions): Fix renaming quick actions issue

- src/backend/effects/builtin/play-sound.js
added flac support for random from folder. 
#2448
> feat: add FLAC support to to play sound random

- src/gui/app/directives/controls/time-input.js
Fixes an issue that prevents the time-input from saving seconds, instead saving minutes.
#2494
Ensured the control will now save seconds properly
> fix: time-input not saving seconds (#2494)

- src/backend/chat/chat-listeners/twitch-chat-listeners.js
Adds chatCommandHandler to the /me onAction handler 
#2552 
tested with commands set to scan whole message and not. commands triggered
> fix: slash me not triggering in commands

- src/backend/integrations/builtin/obs/effects/create-recording-chapter.ts
- src/backend/integrations/builtin/obs/obs-integration.ts
- src/backend/integrations/builtin/obs/obs-remote.ts
Adds an effect to create a recording chapter marker in OBS 30.2 or later
#2609 
Tested saving without chapter name
Tested running on outdated OBS with proper error
Tested running while not recording with proper error
Tested running on unsupported video format with proper error
> Obs chapter markers

- src/backend/integrations/builtin/obs/obs-remote.ts
add obs 30.2 text_gdi+v3 support 
tested with obs 30.2
> feat: add support for obs gdi+v3

- src/backend/notifications/notification-manager.ts
uses error.message rather then the full error object to try to help with log spam
part of to reduce the log spam
#2650
> Fix: notification error log spam

- src/backend/events/filters/builtin/viewer-ranks.js
Fix rank display & rank check in Viewer Rank filter
Manually tested the filter UI and rank check now work
> fix: viewer rank filter

- src/backend/chat/commands/builtin/quotes.ts
- `!quote list` command used poor phrasing. This should make it easier on the eyes.
- A bunch of other places used disparate language. Adjusted them all to be similar, and contraction-free.
> chore: !quote Verbiage Alignment

- src/backend/common/account-access.js
- src/backend/effects/builtin/chat.js
- src/backend/effects/builtin/html.js
- src/backend/effects/builtin/reset-timer.js
- src/backend/effects/builtin/twitch/announcement.ts
- src/backend/games/builtin/heist/heist.js
- src/backend/hotkeys/hotkey-manager.js
- src/backend/integrations/builtin/philips-hue/hue-manager.js
- src/backend/variables/builtin/array/array-find-index.ts
- src/backend/variables/builtin/array/raw-array-find-index.ts
- src/backend/variables/builtin/number/ensure-number.ts
- src/gui/app/directives/controls/dynamic-parameter.js
- src/gui/app/directives/settings/categories/advanced-settings.js
- src/gui/app/directives/settings/categories/backups-settings.js
- src/gui/app/services/commands.service.js
- src/gui/app/services/connection.service.js
- src/gui/app/services/listener.service.js
- src/gui/app/services/logger.service.js
- src/gui/app/services/websocket.service.js
- src/gui/js/plugins/scroll-glue.js
- src/gui/js/plugins/select.js
It'sn't
n/a
No functional changes, all changes in names of properties/methods have been made consistently
n/a
> [Techdebt] Fixed some typos

- src/backend/effects/builtin/file-writer.js
1. Addressed a single misspelling in file-writer.
N/A
N/A
> chore: (effect) trivial misspelling in file-writer

- src/backend/integrations/builtin/obs/variables/input-audio-monitor-type.ts
- src/backend/integrations/builtin/obs/variables/is-connected.ts
- src/backend/integrations/builtin/obs/variables/is-recording.ts
- src/backend/integrations/builtin/obs/variables/is-streaming.ts
- src/backend/integrations/builtin/obs/variables/scene-item-enabled.ts
- src/backend/integrations/builtin/obs/variables/scene-item-name.ts
- $obsInputMonitorType: object -> text
- $obsIsConnected: text -> bool
- $obsIsRecording: text -> bool
- $obsIsStreaming: text -> bool
- $obsSceneItemEnabled: text -> bool
- $obsSceneItemName: number -> text
N/A
> fix: OBS Variable Typing

- src/gui/app/directives/controls/editable-list.js
- src/gui/app/directives/modals/variables/add-or-edit-variable-macro-modal.js
Adds more granular error messages and updates the verbiage around macro variable arguments
Ensured error messages show up only when their condition check fails
Ensured macro vars only save when all conditions pass
> chore: update error messages and verbiage for Macro Variable Arguments

- src/backend/events/builtin/twitch-event-source.js
- src/backend/events/twitch-events.js
- src/backend/events/twitch-events/chat.ts
- src/backend/twitch-api/pubsub/pubsub-client.js
Adds an event for Twitch Chat Cleared
#2686
Ensured clearing chat from Twitch site fires the event with proper user id and name
Ensured clearing chat from Firebot fires the event with proper user id and name
Ensured user id and name are passed properly when simulating event
> feat: twitch chat cleared event

- src/backend/effects/builtin/play-video.js
- src/gui/app/directives/controls/time-input.js
this adds 2 check boxes to the play random clip from twitch 
one for featured only 
one for max age with max age the time input was added so that users can select the amount of time to the current time to get clips from the api request.
and fixed linting
#2594
#1554
while coding and playing with this i was randomly targeting chat users
> feat: twitch clip date and feature

- src/backend/integrations/builtin/obs/effects/transform-obs-source-scale.ts
- src/backend/integrations/builtin/obs/obs-remote.ts
Updates Source Transform to use seconds instead of milliseconds for time to be consistent with the rest of the app
Updates Source Transform to allow rotations < -360 and > 360
Updates Source Transform to allow setting Source Transform for Sources in Groups
Ensured sources in groups can now be transformed
> feat: Improve OBS Source Transform

- src/main.js
Enables text-to-speech on Linux through speech-dispatcher
#1553 
Ensured text-to-speech continues to work on Windows and MacOS systems
Ensured text-to-speech now works on Linux when speech-dispatcher is properly configured
> feat: enable speech-dispatcher for linux

- src/gui/app/directives/effect-option-settings/eosEnterExitAnimations.js
- src/resources/overlay/scss/_animate.scss
adds more animations to the overlay for all overlay effect 
Swirl and Full Screen Slide. 
tried all animations in the overlay
> feat: add animation keyframes

- src/backend/common/screenshot-helpers.ts
- src/backend/effects/builtin/clips.js
- src/backend/effects/builtin/play-video.js
- src/backend/effects/builtin/random-reddit-image.js
- src/backend/effects/builtin/show-image.js
- src/backend/effects/builtin/show-text.js
- src/backend/effects/builtin/take-screenshot.js
- src/gui/app/directives/controls/screenshot-effect-options.js
- src/gui/app/directives/effect-option-settings/eosOverlayRotation.js
added a Z rotation to the show image, show text and play video
if x and y are wanted they can be added later...
created a uniformed layout
#2498
checked all actions in the browser and overlay in OBS.
> feat: add rotation to show image, show text and play video

- src/gui/app/directives/controls/dynamic-parameter.js
- Not even a comment here. These things happen.
N/A
None.
N/A
> "No Comment"

- src/backend/effects/builtin/moderator-ban.js
changed the unban function to the correct unbanUser function
#2809
> fix: unbanuser effect pointing to an incorrect unban function

- src/gui/app/directives/modals/effects/add-edit-preset-effect-list-modal.js
Updates the verbiage inside of "How to trigger from StreamDeck" inside of a Preset List to current verbiage used by the Stream Deck app
N/A
N/A
> chore: update streamdeck website action verbiage for modern app versions

- src/backend/chat/chat-helpers.ts
- src/backend/chat/commands/chat-command-handler.ts
- src/backend/common/settings-access.js
- src/backend/events/filters/builtin-filter-loader.js
- src/backend/events/filters/builtin/shared-chat.ts
- src/backend/variables/builtin/twitch/chat/message/index.ts
- src/backend/variables/builtin/twitch/chat/message/is-shared-chat-message.ts
- src/gui/app/directives/controls/firebot-select.js
- src/gui/app/directives/modals/commands/addOrEditCustomCommand/addOrEditCustomCommandModal.html
- src/gui/app/directives/modals/commands/addOrEditCustomCommand/addOrEditCustomCommandModal.js
- src/gui/app/directives/modals/commands/editSystemCommand/editSystemCommandModal.html
- src/gui/app/directives/modals/commands/editSystemCommand/editSystemCommandModal.js
- src/gui/app/directives/settings/categories/trigger-settings.js
- src/gui/app/services/settings.service.js
- src/types/chat.d.ts
- src/types/commands.d.ts
Add the option for commands and chat-related events to ignore Twitch Shared Chat.
#2838 
Manual testing for new UI has been performed
Manual testing for event filter was performed, ensuring the event does not fire when 'Shared Chat' is set to 'true'
Live testing in a shared chat session is required
Custom Command
System Command
Event Filter
Replace Variable
Application Setting
> feat: Ignore Shared Chat

- src/backend/variables/builtin/utility/file-line-count.ts
this removes the file type restriction from file line count.
#2893
checked that the file line count could be used with html json and txt files
> feat: file count variable to remove file type restriction

- src/backend/variables/builtin/misc/date.ts
- src/backend/variables/builtin/misc/time.ts
- src/backend/variables/builtin/misc/unix-timestamp.ts
updated 
date, unixTimestamp and time variable descriptions to include momentjs link 
and other samples.
> chore: date description to include moment link and other examples

- src/backend/effects/builtin/update-role.ts
Convert customrole effect to typescript
Reduce Twitch user fetching when data is available
N/A
Tested command and chat message event. Any event that provides Twitch user data should work. 
I was unable to test channel rewards due to not being affiliate
Tested handling of viewer DB on/off, and users that are or are not in the DB.
Tested fallback Twitch logic to ensure users not caught by Associated Viewer or ViewerDB check are properly looked up on Twitch API
N/A
> chore: update customrole effect

- src/backend/effects/builtin/celebration.js
- src/backend/effects/builtin/chat-feed-alert.js
- src/backend/effects/builtin/chat.js
- src/backend/effects/builtin/twitch/announcement.ts
celebration
chatFeedAlert
chat
announcement 
var menu was too tall so i changed it to under
> chore(effects): move var menu under on some input fields

- src/backend/variables/builtin/user/ranks/index.ts
register rankLadder variable 
#2995
sent chat message on rank ladder update event
``@$userDisplayName[$user] has achieved the rank of $newRank $rankValueDescription[$rankLadder, $newRank]! ``
``@phroggie has achieved the rank of regular 3000 test1!``
> fix(ranks): rankLadder variable register

- src/backend/viewers/viewer-database.ts
move twitchChat out of the topLevel import to fix circular dependency
and await the sendChatMessage 
#2993
changed test1 currency to trigger output to chat message.
> fix(ranks): ranks not sending chat messages

- src/gui/app/services/currency.service.js
Removed ``.id`` so it get the actual id.
#3035
Purged a test currency and it's no longer returning undefined and actual purge it
> fix(Currency purge)

- src/gui/app/directives/controls/sound-player.js
change load to canplay to prevent a null error 
#3028
opened and closed the play sound effect
> fix(effects): sound service error (#3028)

- src/backend/twitch-api/chatter-poll.ts
Tweak a minor misspelling in IRC viewer polling for error logging.
N/A
> fix(twitch): Minor Misspelling

- src/backend/currency/currency-command-manager.ts
add targeted command for currency
useage ``currency @username``
#3018
checked existing commands and new command output all errors and valid chat replies.
> feat(commands): targetable currency command (#3018)

- src/backend/variables/builtin/currency/currency-rank.ts
- src/backend/variables/builtin/currency/currency.ts
use trigger.metadata.username as the username if none is supplied 
for currencyRank and currency Variables 
#3021
ensured the name was passed into the apparated functions when no name was supplied
> fix(variables): currency variables to get user from trigger (#3021)

- src/backend/roles/chat-roles-manager.ts
- src/backend/variables/builtin/twitch/index.ts
- src/backend/variables/builtin/twitch/vip.ts
add a variable to get an array of all vips in a channel 
#2723
added to chat effect and it spat out the array text of all vips
> feat(variables): vip array variable (#2723)

- src/backend/variables/builtin/number/number-max.ts
- src/backend/variables/builtin/number/number-min.ts
Add array parameters to $min and $max number variables
#2987
Ensured variables return proper values under the following conditions:
- single number
- multiple numbers
- single array
- multiple arrays
- combination of arrays and raw numbers
>  feat: add array parameters to $min and $max (#2987) 

- src/backend/twitch-api/eventsub/eventsub-client.ts
- Forgot to pull the parameter supplied to [buildViewerFirebotChatMessageFromAutoModMessage](https://github.com/crowbartools/Firebot/blob/2dcafe35d8db37358bbe78070a27701669b1f61e/src/backend/chat/chat-helpers.ts#L524) despite hard-coding it in there.
N/A
> fix(eventsub): Minor Oversight in AutoMod

- src/types/settings.ts
- Add appropriate default settings for DashboardLayout (taken from [chatMessagesController](<https://github.com/crowbartools/Firebot/blob/2604c3fd1962ac1fcd14ef8d8b89c743424a1938/src/gui/app/controllers/chat-messages.controller.js#L49>))
- Add typings for QuickActions settings (taken from [quickActionManager](<https://github.com/crowbartools/Firebot/blob/2604c3fd1962ac1fcd14ef8d8b89c743424a1938/src/backend/quick-actions/quick-action-manager.js#L58>)), since I'm already here
#3095 
Enough to verify that no ill effects are seen, and that my new profile's log files are hundreds of megabytes per minute smaller.
N/A
> fix(Settings): Log Spam On First Activity Feed Event (#3095)

- src/backend/effects/builtin/shoutout.js
add wait for shoutout to finish to firebots shoutout
#3137
ensure that the effect finishes all animations and then shows the runs the next effect.
> feat(effects): add wait for shoutout to finish to firebots shoutout (#3137)

- src/backend/effects/builtin/play-video.js
add effect output to allow duration to be used as a variable for other effects 
#3138
the duration variable outputs the the correct variable
> feat(effects): add effect output to play video(#3138)

- src/gui/app/directives/modals/variables/add-or-edit-variable-macro-modal.js
make variable macro expression min length 1
#3144
ensured the variable macro saved with a expression of 0 and was usable
> feat(variables): variable macro expression length(#3144)

- src/backend/variables/builtin/utility/file-read.ts
add readFile to array 
#3119
reading a file that is 
```js
string 3 true
string 4 false
string 5 true
string 1 false
string 9 true
string 546 false
string 66 true
string 32 true
string 34 true
```
results in the following array
```log
[2025-04-18 20:56:53.0437] - info: ["string 3 true","string 4 false","string 5 true","string 1 false","string 9 true","string 546 false","string 66 true","string 32 true","string 34 true",""]
```
> feat(variables): Add array to readFile(#3119)

- src/backend/effects/builtin/chat-feed-alert.js
TL;DR: A "chat feed alert" will now be added to the chat feed even if chat is not connected.
_Longer:_
The current implementation requires that chat be connected in order for a "chat feed alert" to add something to the chat feed. If chat isn't connected, the chat feed alert is never added. (This does result in an error being reported in Firebot's log due to the failed dependency.)
This PR removes the requirement that chat be connected in order for a "chat feed alert" to add something.
CAVEAT: There is an overlay that darkens the chat feed when chat is disconnected, and this darkens any chat feed alerts as well. Reposting the screen shot from @ebiggz in the Discord thread:
Once chat is connected, that overlay is removed from the chat dashboard, and the chat feed alert will appear normally. …
> feat(effects): Remove chat dependency on chat feed alert (#3169)

- src/backend/chat/chat-listeners/twitch-chat-listeners.js
This PR removes the pubsub-era code for detecting resub publishes made by users that were gifted multiple months of sub.
#3166
None
> fix(events): duplicate sub publish on multi-month gift (#3166)
