crowbartools/Firebot

- gui/index.html
- gui/js/global.js
- lib/interactive/beam-connect.js
Added the ability to toggle interactive via the status indicators, added a console log line to confirm interactive disconnection, made the chat/interactive status indicators visible on the main page again and changed the source comment about Global Killswitch CTRL+Backspace to CTRL+ALT+F12.
> Added the ability to toggle interactive via the status indicators

- gui/js/interactive/controls-editor.js
- lib/interactive/handlers/game-controls/emulator.js
- lib/interactive/handlers/game-controls/keytranslator.js
I wanted an interactive button to be able to click my mouse but I didn't see the option to do so and I didn't want to give full joystick control to the viewers either (however at a quick glance, it doesn't look like joysticks can or do support mouse clicks anyhow).
I updated my fork to add this feature and wasn't sure if this is something you want in the main repro but I figured I'd toss this up anyway and see what you think. It covers both emulators, single press/holding cases, and updates the autocomplete list. 
For the end user, this allows them to input: "leftmouse", "middlemouse", and "rightmouse" as a key for a Game Control button. 
My use case: I currently play a lot of PlayerUnknown's Battlegrounds and thought it would be fun to allow viewers to occasionally fire my weapon at …
> Enable mouse buttons to be specified for a game control button

- gui/js/interactive/controls-editor.js
- gui/js/interactive/handler/mediaHandler.js
- lib/interactive/handlers/mediaProcessor.js
- overlay/js/main.js
This should handle #168, and if the streamer leaves the size fields blank the image will be forced to 100x100px as a failsafe. The only downside I see with this method is that they have to know the pixel size of the images to get the proportions right. Might have to look into doing this another way at some point, maybe require the pixel size of the imagefile  then have a percent field that can be used with a jquery function to scale the image while keeping the correct proportions.
The way I added image size controls in the first place was flawed as it was giving images the whole container div as a "playground" which blew them up in all directions. Rewrote it to require pixel sizes for now.
> Imageoverlay size handling

- gui/css/main.css
- gui/index.html
- gui/js/interactive/controls-editor.js
- gui/js/interactive/interactive-board.js
- gui/scss/_interactive.scss
Addresses #179 
I replaced all instances of the button dropdowns. These were located in the cooldown groups area and the cooldown button effect. It's now a scrollable list of all buttons that you can just check or uncheck.
I also added a container to each individual setting for all effects so that we can space those out more and make them a bit easier to distinguish. If we need to give them background colors or something later it'll be much easier now.
For all of the effect-info divs I added bootstrap alert styling. Regular info is in a blue box now and warnings are in red boxes. Should draw more attention now.
> Replacing button dropdowns, ui changes.

- gui/js/login.js
Fix for possible issue when using the shortcut CTRL+ALT+F12, the string it compares against is "Connected - Click to Disconnect", not "Connected." so it will never be seen as connected and never do anything else than to reconnect on triggering the shortcut. This cuts of the remaining characters after the ninth character so that it's seen as "Connected" instead of the whole string from the button.
> Fix for possible shortcut issue.

- gui/app/services/effectHelperService.js
- gui/app/templates/interactive/effect-options/change-scene.html
I missed a couple things in the last pull request. Sorry about that.
For some reason I didn't see the html file in the PR so I didn't review it till after the merge. But made a suggested change here that will allow us to reuse the group select checkboxes section, instead of having it in two places. 
I also use ng-show and ng-hide for the info textbox to showcase an alternative to ng-if. 
ng-show/ng-hide and ng-if both have their uses and it kinda depends on the situation for which is better. 
ng-if completely removes and adds the html element from the DOM (so its a little more expensive on large elements) and ng-show/hide just adds the "display: none;" css property to an element (so its faster, but sometimes you might not want the element lurking around hidden).
I also gave bad advice on …
> "Change Scene" Effect Tweaks

- lib/interactive/auto-grouper.js
This should make it so that the auto group functionality will only activate if the person has user groups on the board. This should also significantly lower the amount of times we need to read the controls file for auto grouping while connected.
> Auto grouping changes.

- gui/app/services/boardService.js
- gui/app/services/settingsService.js
Moved the operations of getting boardIds into settings.json to lower amount of file operations during startup and in combinations with updatechecker this will really reduce the amounts of file writing operations during startup so it loads a lot quicker when you have huge boards loaded into the bot.
It might take a bit of loading when going from v3 to v4 since it has to read through the board files to get all the IDs and put them into settings.json. On future launches it will not read these files on load as it has the IDs in the right place. The same goes for from v4 pre knownBoards and the updated checker.
> Putting knownBoards into settings.json to lower amount of file operations.

- gui/app/services/effectHelperService.js
- gui/app/services/groupsService.js
This will make it so that change groups and change scenes button effects will only show active groups on the current board for selection.
There is a new function in the groupsService called "getActiveGroups" which returns an array of active groups for the current board.
To Test:
What happens if you set up a change scene button and then deactivate one of the groups you had selected for that button.
> Button effects group fix

- gui/app/services/connectionService.js
- gui/app/services/utilityService.js
This is a hotfix that would allow logins to work in 4.0 again. 
Currently it seems Mixer is requiring a client secret even when our auth client isn't set up to use one.
This change includes an arbitrary string ("firebot") as the client secret for auth requests.
If this ends up being a temporary issue with Mixer, we can delete this PR.
> Include an arbitrary secret in auth request

- gui/app/services/settingsService.js
This adds a simple caching layer into the settingsService. 
This means that we wont have to go to the json file every single time we need a setting, which can happen a lot with $scope updates for each setting we may be watching. If you are curious how often that is, throw a console.log in the `getDataFromFile` function in settingsService and watch the console light up when you start switching tabs and doing things.  So ultimately, this should help make sure performance stays nice and smooth. 
The cache elements shouldn't ever get stale as long as we always update and retrieve settings via the settingsService.
I also added an optional argument to the `getDataFromFile` function to allow us to force the cache to be updated (aka it gets the setting from the file) should we ever need it.
> Cache layer for Settings

- package.json
Added a version string to control the name of the app shown on the desktop shortcut to the pack:win64 line plus copying necessary files over into the dist folder after building the Electron Package.
Added a script line for auto build electron package as well as installer package.
> Added version string + package script

- gui/app/services/boardService.js
- gui/app/templates/interactive/_interactive.html
**Description:**
This change will make it so that we're using board id numbers instead of board names for our control filenames.
**Reason:**
We were running into issues with people changing the name of their board, and then losing all of their settings in Firebot. There were also cases of people naming their board things that did not work great with file systems.
**Warnings**
This will automatically convert all current controls files to this new file format. It will check when Firebot runs and then rename files from board name based files to version id based files. The end user shouldn't notice any changes within the app.
However, since we're renaming controls files there is the possibility of a bug that causes data loss that I didn't catch.
> Switch over to using board id number for filenames.

- gui/app/templates/interactive/modals/editControlEffectsModal.html
- lib/common/mixer-interactive.js
- lib/interactive/control-router.js
- lib/interactive/threshold.js
This adds button thresholds with updating progress bars. 
- Threshold (number of uses) is set per button.
- Progress bar on Mixer front end updates live.
- Progress bar resets when button fires.
- Threshold check is skipped and button run if threshold is not entered or set to 0 or 1.
- Events logged in app if button not fired due to threshold check.
- Threshold counts are cleared on disconnect just like cooldowns.
- Manual button presses in app do not go through threshold checks.
> Button thresholds with updating progress bars.

- gui/app/controllers/moderationController.js
- gui/app/services/groupsService.js
- lib/interactive/control-router.js
- lib/interactive/helpers/sparkExemptManager.js
- lib/interactive/permissions.js
This should fix spark exemptions for most people.
Rewrote spark exemptions so that it no longer depends on the groups assigned to the active board. Now, spark exemptions use logic from our permissions code. It will pull information from Mixer for each interaction. 
One thing is that currently this change means we're checking the same info twice for interactive buttons. Once for permissions, and once for spark exempt. We can probably clean this up and make only one call instead. But, I don't think it'll be a problem for 99% of people since they won't hit rate limits.
Notes:
- To simplify things, streamers are no longer charged sparks in their own channels ever. 
- It no longer matters which groups are assigned to which scenes. You can give exempt status to groups no matter what.
> Fixes spark exemptions.

- backend/effects/builtin/showImage.js
This adds in the ability for the Show Image effect to pull a random image from a folder. 
- Gets all files in given folder path.
- Filters out anything that isn't: .jpg, .jpeg, .gif. png
- Selects one randomly.
- Sends it to the overlay as if it were the "local file" option.
> Add ability to get a random image from a folder.

- backend/chat/active-chatters.js
- backend/database/currencyDatabase.js
- backend/effects/builtin/currency.js
- backend/restrictions/builtin/activeChatUsers.js
- backend/roles/firebot-roles-manager.js
- gui/app/services/viewerRolesService.js
- gui/app/templates/_viewerroles.html
- shared/firebot-roles.js
Changes:
- Set up active chatter as a "Firebot Role".
- Add Firebot Roles to the bonus currency area on the create/edit currency modal.
- Add Firebot Roles to the currency effect "role" option.
- Show Firebot Roles on the Viewer Roles screen.
- Add "Set" option to currency effect that will just set the currency to a specific value.
- Create isActiveChatterUsername function to see if a specific person is active.
- Cleaned up areas to use the isActiveChatterUsername function.
Notes:
- We already have "Active Viewers" as a filter. So, I left Firebot Roles out of the "permissions" filter. If we add more Firebot Roles later on that we want to show in the permissions area, we might need to figure out that problem. Probably "Active Viewers" would just map to that Firebot Role or something.
> Active Chatter and Currency Adjustments

- backend/chat/active-chatters.js
- backend/database/userDatabase.js
- gui/app/directives/modals/viewers/viewerDetailsModal.js
This puts a toggle into the viewer modal that will allow people to exempt certain users from the "Active Viewers" list. This will allow people to exclude their bots from things like the $randomActiveViewer variables.
If we decide to put in a separate $randomActiveMixplay variable for mixplay connections, this same toggle could exempt from that as well.
> Add ability to remove users from activeViewerList.

- backend/effects/builtin/cooldowns.js
- backend/interactive/control-manager.js
- backend/interactive/cooldown-manager.js
- backend/interactive/mixplay.js
Changes:
- Add ability to cooldown buttons or cooldown groups.
- Add options for updating, adding, or subtracting to cooldown.
-- Updating allows for force updating, updating if new cooldown is longer, or updating if new cooldown is shorter.
-- Adding and subtracting to the current cooldown time.
- This has fallback for "old" cooldown effects and will default to cooling down buttons if the cooldown is longer than the current cooldown.
- Makes cooldowns async.
Testing:
- Individual cooldown set on button itself: OK
- Cooldown groups: OK
- Individual cooldown set on button AND button in cooldown group: OK
- Button in cooldown group AND button has cooldown effect that targets itself: OK
- Button has individual cooldown, cooldown group, and effect that targets self: OK
- Button is in cooldown …
> V5 cooldown effect updates

- backend/common/mixer-chat.js
- backend/common/settings-access.js
- backend/interactive/control-manager.js
- backend/interactive/mixplay.js
- backend/restrictions/builtin/activeChatUsers.js
- backend/roles/firebot-roles-manager.js
- backend/roles/role-managers/active-chatters.js
- backend/roles/role-managers/active-mixplay-users.js
- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/active-chat-user-count.js
- backend/variables/builtin/active-mixplay-user-count.js
- backend/variables/builtin/random-active-mixplay-user.js
- backend/variables/builtin/random-active-viewer.js
- backend/variables/builtin/random-mixplay-user.js
- gui/app/controllers/settingsController.js
- gui/app/directives/modals/viewers/viewerDetailsModal.js
- gui/app/services/settingsService.js
- gui/app/templates/_settings.html
- shared/firebot-roles.js
Changes:
- Keep list of active mixplay users on backend.
- Add randomActiveMixplayUser variable
- Add randomMixplayUser variable
- Add activeMixplayUserCount variable
- Add settings to turn active mixplay list on or off and adjust inactive timeout.
- Move active-chatters file and active-mixplay-users files to the roles folder to keep role specific logic together.
Tests:
- Tested to make sure tagging a person in the viewer db to keep them off active lists works on this as well.
- Tested all three new variables.
- Tested to make sure anonymous users are not placed on the active user list. (Would be pointless for the vast majority of uses).
Notes:
- This moves the active-chatters file, so it could have impact on old active chatters variable. But, I believe I got everything pointing to the …
> V5 mixplay active users

- backend/variables/builtin/random-active-viewer.js
Implements #685 
Usage:
$randomActiveViewer[Fun Group Name]
Changes:
- Implements an optional parameter for the randomActiveViewer variable that allows you to pass a role name.
- Backend to compare role user list against active user list and create a new array that contains only people in both.
- Pick one from the new list at random and output it.
Note:
We may look at a way to clarify which parameters are optional in the future in the variable picker. Right now we're just putting it in the descriptive text, but the actual variable usage shows the parameter.
> Optional argument to get an active user in a custom role.

- backend/effects/builtin/update-role.js
- backend/roles/custom-roles-manager.js
Implements #690 
Changes:
- Rearrange "update viewer roles" effect. You'll now choose the action before you choose a user.
- Add a "remove all from role" action to the effect.
- Implement backend, which just sets the viewers in said role to an empty array.
This will allow people to clear roles entirely for the purpose of resetting games, votes, or other things without needing to log everyone to a file and then loop through the file and remove people one by one.
> Clear all users in role

- backend/interactive/cooldown-manager.js
Should fix #701 
Changes:
- Remove an extra loop.
- Return ttl immediately if it's already 0, instead of comparing with moment.
For whatever reason I had decided in my old code to do an additional loop that wasn't needed. So, for each control ID I was looping through the control IDs again. I believe this was causing cooldowns to be applied twice and cause issues. This would have only affected the "add" and "subtract" cooldowns if updating a cooldown group with multiple buttons.
> Fix math cooldowns

- backend/effects/builtin/conditional-effects/conditions/builtin/viewer-roles.js
Implements #742 
Changes:
- Update "include" to "is in role" and "doesn't include" to "isn't in role".
- Make sure we leave the "include" and "doesn't include" in as a fallback for previous versions.
Why?
This makes it easier to see what exactly this conditional is doing without needing to click in on it to edit it.
> Cleanup role conditional label.

- backend/common/user-access.js
- backend/effects/builtin/conditional-effects/conditions/builtin-condition-loader.js
- backend/effects/builtin/conditional-effects/conditions/builtin/follow-check.js
- backend/restrictions/builtin-restrictions-loader.js
- backend/restrictions/builtin/followCheck.js
- package-lock.json
Implements #744 
Changes:
- New function in user-access that allows us to determine if a user is following certain streamers.
- Add follow check restriction.
- Add follow check conditional.
This will allow people to put buttons behind a list of required follows. This will be useful for people who want to cross promote other streamers by unlocking buttons and effects. It will also be useful in limiting your buttons to being follower only.
Downside:
This makes API calls. So, if a conditional or restriction is put onto something that is spammed a ton (like a chat message event) they could maybe hit the API call limit. This should cause firebot to return false on any other follow checks, but nothing should break.
> Follower restrictions

- backend/effects/builtin/activeUserLists.js
Implements #812 
Changes:
- Adds an "all" option for the active user list effect.
This allows users to clear, add to, or remove from all active user lists with one effect instead of needing multiple.
> Add an "all" option for active user list effect.

- backend/effects/builtin/playSound.js
Implements #693 
Changes:
- Updates play sound effect to add option to choose between "local file" or "random from folder".
- Local file is the default for all sound effects existing before this point.
Notes:
- The random effect is limited to the same file types as the local file is... mp3, ogg, and wav.
Use Cases:
- For events, like follows and subs, a user can now build a "follow sounds" folder and play one at random when someone follows.
- Fart sounds folder.
> Random sound from folder

- backend/chat/commands/commandHandler.js
- backend/effects/builtin/cooldown-command.js
- package-lock.json
Implements #964 
This adds in a clear option for the command cooldowns effect. You can clear the global cooldown, a user specific cooldown, or both.
Changes:
- Add "action" option to clear command cooldown effects. It has "add" and "clear". 
- Add options to clear global and/or user specific cooldowns.
> #964 Create a clear option to clear command cooldowns.

- backend/effects/builtin/celebration.js
Implements #930 
Changes:
- Sets z-index on celebration overlay higher so that it will show above images.
- Fixes an issue where the celebration canvas was not being removed after the animation was done.
> #930 Celebration fixes

- backend/restrictions/builtin/permissions.js
Minor update to display team roles separately from twitch (and custom) roles in the permissions view.
Related to the team roles feature: https://github.com/crowbartools/Firebot/issues/1034
Followup for the team roles PR: https://github.com/crowbartools/Firebot/pull/1065
> Separate team roles from twitch roles in the permissions view

- backend/chat/twitch-chat.js
This makes it so that the chat message event will trigger when the user chats as the streamer account in Firebot's chat window.
#1051 
I tested by creating a !test command that had my streamer account reply with who chatted. I then typed !test into the firebot chat window and got the response that I chatted. This did not trigger the chat message event a second time, which is what I would expect.
> Fix message event not triggering on streamer chatting in firebot chat.

- backend/common/common-listeners.js
- backend/events/builtin/firebotEventSource.js
- backend/variables/builtin/chat-message.js
- gui/app/directives/chat/chat-message.js
- gui/app/services/chatMessagesService.js
This adds in an option to manually trigger a "message highlight" event from the Firebot chat window. The use case that inspired this was the ability to highlight a specific message in the overlay in order to bring more attention to it.
There is a "highlight message" channel points reward that I didn't think about until this was completed. Do you think the naming of this event may be confusing at all?
N/A
> V5 Manual Highlight

- gui/app/directives/modals/events/addOrEditEventModal.js
Shows the enable-disable setting at event creation, instead of only displaying it after an event has been created.
n/a
> Show the enable-disable setting during event creation

- backend/common/handlers/custom-scripts/custom-script-helpers.js
Currency, custom variable, game, timer, … managers are already available to custom scripts. The counterManager was missing. This PR adds it.
Adding the counter-id in a custom script as parameter is not really nice, by adding the `counterManager` only the name has to be added, the script can then query the id from there.
n/a
> Make Counter Manager Available to Custom Scripts

- backend/variables/builtin/chat-message.js
- gui/app/services/chatMessagesService.js
From what I can tell, events seem to use messageText where other things tend to use chatMessage. We tried updating messageText to chatMessage for the release of manual highlighting, but it caused problems.
This changes chatMessage back to messageText which should fix the $chatMessage variable for events.
#1104 
1. Create a new highlight message or chat message event.
2. Have it output a chat message or overlay text.
3. Put in a $chatMessage variable in the effect.
4. Fire the event and confirm chatMessage gets parsed correctly.
Tested on message highlight and chat message events.
> #1104 V5 chat message variable fix

- gui/app/controllers/eventsController.js
The events controller keeps trying to find the event set you left the tab on, after deleting that particular event set through Remove Setup.
Events tab keeps trying to find event set after removing setup https://github.com/crowbartools/Firebot/issues/1114
Went to the evens tab, clicked on the event set that is going to be removed through Remove Setup. Removed setup, went back to events tab to make sure it defaulted to the main events.
> Fix bug where events controller keeps trying to find a deleted event set

- backend/chat/commands/command-access.js
- backend/import/setups/setup-importer.js
- backend/import/v4/areas/v4-commands-importer.js
This splits the importing and saving in `command-access.js`, so that the saving functionality can be reused (which is what I need for the toggle command effect feature). 
Preparation for the toggle command effect feature: https://github.com/crowbartools/Firebot/issues/1068.
Imported a new command, which was correctly saved. Then modified that command and imported the original one, which overrode the modified one correctly.
> Split command import functionality from command saving functionality in command access

- gui/app/directives/misc/sysCommandRow.js
Adds a button to the system commands list that toggles the active state of a command, so that you don't have to open the modal first.
n/a
Clicked the button for both state, checked if in the edit modal if "Is Active" was in the right state.
> Add a button to the system commands list that toggles the active state of a command

- backend/database/currencyDatabase.js
- backend/effects/builtin/conditional-effects/conditions/builtin/viewer-roles.js
- backend/events/filters/builtin/viewerRoles.js
- backend/games/builtin/heist/heist-command.js
- backend/games/builtin/slots/spin-command.js
- backend/games/builtin/trivia/trivia-command.js
- backend/restrictions/builtin/permissions.js
- backend/roles/custom-roles-manager.js
- backend/roles/team-roles-manager.js
- gui/app/services/viewerRolesService.js
- shared/twitch-roles.js
The stream team roles were not working in the Viewers Roles condition because `teamRolesManager.getAllTeamRolesForViewer` returns a Promise that we were not awaiting on. 
While I was at it I also did some general clean up of really old code + added some JSDocs.
@CaveMobster I am requesting a review from you as you worked in this recently and are the most familiar, so let me know if I forgot anything. I am also wondering if you would be willing pull down this branch and briefly test the Viewers Roles condition to confirm the fix. I am not in any stream teams so I cannot do so myself :( 
#1130
> Fixes stream teams not working in the Viewers Roles condition + general clean up

- backend/events/builtin/twitchEventSource.js
- backend/events/filters/builtin/cheer-bits-amount.js
- backend/events/twitch-events/cheer.js
- backend/twitch-api/pubsub/pubsub-client.js
- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/cheer-bits.js
- backend/variables/builtin/cheer-total-bits.js
This adds a variable to display the total amount of bits cheered in the channel by the associated user.
https://github.com/crowbartools/Firebot/issues/1127
I tested with the test function, unfortunately no way to do live testing.
> Add a variable for total bits cheered in the channel

- backend/events/builtin/twitchEventSource.js
- backend/events/filters/builtin/username.js
- backend/events/filters/builtin/viewerRoles.js
- backend/events/twitch-events/whisper.js
- backend/twitch-api/pubsub/pubsub-client.js
- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/whisper-message.js
**Important:** Please look at https://github.com/crowbartools/Firebot/pull/1137 (total bits) first, as there are going to be conflicts.
This adds an event to catch whispers sent to the streamer.
https://github.com/crowbartools/Firebot/issues/1032
I made an event with a chat alert effect that includes both username and the message, then whispered my streamer account from my bot account.
> Add an event to catch whispers

- gui/app/controllers/commandsController.js
- gui/app/directives/misc/subcommandRow.js
- gui/app/directives/misc/sysCommandRow.js
- gui/app/templates/chat/_commands.html
Fixes typos in the `getPermissionType` function name.
n/a
> Fix typos in the getPermissionType functions

- backend/chat/chat-listeners/twitch-chat-listeners.js
- backend/chat/twitch-chat.js
- backend/events/twitch-events.js
- backend/twitch-api/follow-poll.js
- backend/twitch-api/pubsub/pubsub-client.js
This is refactor to group all of the twitch events, so that only one import is needed in `pubsub-client.js` and `twitch-chat-listeners.js`. 
n/a
Checked if the chat message and viewer events still worked as before.
> Refactor the twitch events imports to use a general export module

- backend/events/twitch-events/sub.js
This fixes the situations where `totalMonths` and `streak` for subs are undefined, for example when someone subscribes on the channel for the first time.
https://github.com/crowbartools/Firebot/issues/1151
I can't really test this other than firing a manual event. Unless there is another way to test it?
> Add a default value when cumulative months and streak are not defined

- backend/events/twitch-events/sub.js
- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/sub-message.js
This adds a variable to the subscription event to display the resub message if it's available.
https://github.com/crowbartools/Firebot/issues/1186
I temporarily hardcoded the return value of the variable to test if the variable itself is working. Unfortunately there is no way to test an actual sub message.
> Add a variable for sub messages

- backend/chat/chat-listeners/listeners/chat-message-streamer-listener.js
- backend/chat/chat-listeners/twitch-chat-listeners.js
- backend/chat/moderation/chat-moderation-manager.js
- backend/chat/moderation/url-permit-command.js
- gui/app/controllers/moderation.controller.js
- gui/app/services/chat-moderation.service.js
- gui/app/templates/_moderation.html
- gui/scss/core/_moderation.scss
This adds a url moderation feature to the moderation tools. When view time is enabled, it will check for both exempt roles and view time, otherwise it will only check for exempt roles. 
It also automatically adds a !permit system command with which viewers can be temporarily be permitted to post urls, the default duration (30 seconds) of that permit can be adjusted by the user.
https://github.com/crowbartools/Firebot/issues/1167
The following cases were tested:
- Viewer time disabled with and without message and variables
- Viewer time enabled with and without message and variables
- Exempt roles active with and without viewer time enabled
- Permit command with and without message and variables
- Permit command with different permit durations
- Permit command with multiple users
> Add a url moderation feature to the moderation tools

- backend/chat/moderation/chat-moderation-manager.js
When 2 hours is the minimum view time in the url moderation feature, manually setting a viewer to 2 hours of view time would still cause their message to get deleted. This fixes that issue.
n/a
> Fix the exact minimum view time not being included in the condition

- backend/common/common-listeners.js
- backend/events/builtin/firebotEventSource.js
- backend/events/filters/builtin-filter-loader.js
- backend/events/filters/builtin/stream-category.js
- gui/app/directives/modals/misc/edit-stream-info-modal.js
This adds an event to fire when the category is changed. Useful when you want certain commands and events (and timers soon) to toggle when you are streaming to a specific category.
n/a
I tested multiple categories through both the filter and the conditional effect with the `$game` variable as the condition.
> Add an event to fire when the stream category is edited through the dashboard

- backend/events/twitch-events/gift-sub.js
- backend/twitch-api/pubsub/pubsub-client.js
This workaround takes care of two things:
1. It checks for the right context in the pubsub listener, since `isGift` only checks for `subgift`, and not for `resubgift`, `anonsubgift` and `anonresubgift`.
2. Since the package's `userDisplayName` also only checks for the `subgift` context, it now tries to access `recipient_display_name` straight from the data, and falls back to `userDisplayName` if it can't find it.
https://github.com/crowbartools/Firebot/issues/1241
> Add a workaround to return the correct username for multi month gift subs

- backend/effects/builtin/run-program.js
Missed a `logger.warning` typo in the run program effect, changed it to `logger.warn` so that it doesn't fail due to wrong function call when running a program through the run program effect.
> Forgot a typo in the run-program effect

- backend/chat/chat-helpers.js
- backend/common/handlers/chatProcessor.js
- gui/app/directives/chat/chat-autocomplete-menu.component.js
- package-lock.json
This PR changes the chat connect chat to use the Helix API so that cheer emotes and follower emotes will be displayed when sent from the dashboard chat.
https://github.com/crowbartools/Firebot/issues/1261
Tested all emote types (sub, cheer, follower) from dashboard chat to Twitch chat and the other way around.
> Update the chat connect to include cheer and follower emotes

- backend/effects/builtin/playSound.js
Added `effect.overlayInstance` to the data sent from Firebot to the overlay so the overlay can route the sound effect to the correct overlay instance instead of defaulting it to the default overlay.
#1272 
✔️ - Tested with both OBS and Chrome to see that the sound effect actually plays in the correct overlay instance.
> Overlay sound effect fix - related to #1272

- backend/events/twitch-events/gift-sub.js
This fixes the gifter username from returning null/UnknownUser when it's a multimonth gift sub.
n/a
n/a :(
> Fix the gifter username returning null in case of a multimonth gift sub

- gui/app/controllers/channel-rewards.controller.js
- gui/scss/core/_controls.scss
Add the option to toggle the paused status of a channel reward. Particularly useful since Twitch doesn't provide a clear overview and option for this, especially when a reward is set to skip the reward queue.
n/a
Tested the status view in the table, tested if the reward actually gets paused on Twitch.
> Add the option to toggle the paused status of a channel reward

- backend/events/builtin/twitchEventSource.js
- backend/events/twitch-events/cheer.js
- backend/variables/builtin/cheer-message.js
- backend/variables/builtin/sub-message.js
The subscription message is not being populated at the moment due to a difference between what the event data provides(`subMessage`) and what the built-in expects (`message`).
This PR implements the following:
- Use `subMessage` in the built-in variable evaluation to return the actual message.
- Populate `subMessage` when triggering an event manually for testing.
- Normalize `cheer` event so that is uses `cheerMessage` instead of `message` (all the other event uses distinct names for their message property [ie.: `subMessage`, `chatMessage`, etc....])
N/A - Didn't open an issue for this bug.
Tested receiving subs via Twitch + test triggers.
No UI change applicable.
> fix: subMessage not populated

- backend/effects/builtin/html.js
- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/text-encode-for-html.js
- gui/app/templates/interactive/effect-options/html.html
- package-lock.json
- package.json
Added the built-in variable $encodeForHtml which properly escapes HTML entities.
This allows the safe use of $variables within HTML templates for the HTML effect.
- Built local version
- Tested the variable within an HTML template
- Tested injection scenarios to make sure they are not possible (cheerMessage: `hello <strong>world</strong>`)
> feat: added $encodeForHtml for safe variable use in HTML templates

- gui/app/services/preset-effect-lists.service.js
Corrected bug that prevented the effect list effect from properly restoring setting when reopening.
Fix for #1286 
1. Created an effect list effect
2. Used a preset effect list
3. Saved
4. Reopened the dialog
N/A
> fix: settings not restoring in run effect-list/preset

- gui/app/directives/modals/chat/edit-activity-events-modal.js
- gui/app/directives/modals/misc/chat-settings-modal.js
- gui/app/directives/modals/viewers/editColumnsModal.js
- gui/scss/core/_controls.scss
The `tgl` css class used `display: none` to change the appearance of the toggle, but that makes it inaccessible for screen readers. This PR replaces `display: none` with the `sr-only` class, and adds aria labels for clarity.
https://github.com/crowbartools/Firebot/issues/1030
Tested if the settings are still functional, and tested with NVDA if all settings are properly accessible and clear in description.
> Make the chat settings accessible for screen readers

- backend/effects/builtin/playSound.js
- backend/integrations/builtin/aws/text-to-speech-polly-effect.js
- Fixed Amazon Polly playing in the wrong overlay instance (#1303)
- Amazon Polly was being wrongly referred to as "AWS Polly", this has been corrected
- Fixed Play Sound effect "Wait for Sound" not working when playing a sound from a folder. ( #1309)
#1303,  #1309
- Tested playing polly in a custom overlay instance
- Tested playing a sound from a folder and see if it waited properly
> fix: Amazon Polly playing in wrong overlay instance (#1303)

- backend/twitch-api/api.js
- backend/twitch-api/frontend-twitch-listeners.js
- backend/twitch-api/resource/stream-tags.js
- gui/app/app-main.js
- gui/app/directives/modals/misc/edit-stream-info-modal.js
- gui/app/index.html
- gui/app/services/stream-tags.service.js
- gui/scss/core/_global.scss
This adds an option in the stream info modal to add and remove tags for the channel. 
https://github.com/crowbartools/Firebot/issues/1280
- Added tags to the max of 5, and removing them to see if the UI behaves correctly
- Tried adding double tags to verify that they don't get added
- Saved an empty tag list and a populated tag list
- Clicked the Add Tag button before the tags were loaded to make sure it doesn't open the select modal
- Checked accessibility (as much as possible with the current components)
5 tags (the maximum that Twitch allows)
Less than 5 tags
Tag selecter
> #1280 stream info tags

- backend/effects/builtin/currency.js
- gui/app/services/viewer-roles.service.js
- shared/mixer-roles.js
The Update Currency effect still had Mixer roles (RIP) instead of Twitch roles. This PR fixes that, and I also added clarification that the currency update for roles is for online role users. I will add an option to update a currency for offline roles in a separate PR.
https://github.com/crowbartools/Firebot/issues/1260 and https://github.com/crowbartools/Firebot/issues/1270
Couldn't do any online fixing at the moment, but I did test if all roles showed up correctly.
> #1260 update currency viewer roles

- backend/chat/moderation/raid-message-checker.js
Currently when using the spam raid command with the ban/block option on a chat that solely consists of unique messages, it will ban and block the account of the first message it encounters and takes that as the raid message. This PR adds a minimum check of 2, so that other accounts don't get accidentally banned in case it's used incorrectly.
Tested double and unique messages.
> Add a check in case the cache only consists of unique messages

- backend/chat/commands/builtin/spam-raid-protection.js
This adds subcommands to toggle the settings for spam raid protection command.
Tested the command with all subcommands as well as without.
> Spam raid protection subcommands

- backend/restrictions/builtin-restrictions-loader.js
- backend/restrictions/builtin/time-range.js
This implements a "Time Range" restriction so that people can setup things to only run during certain times of the day. Example use case is a "sing me a song" command that you dont want to run after 10pm.
#902 
- Apply restriction to a command and run command while in time range.
- Apply restriction to a command and run command while outside of the time range.
- Set a time range that crosses over midnight to make sure that day overlapping works.
- Set a time range where the end time is before the start time (app assumes that you meant that time the following day)
This is meant to be a daily time range. Any longer length of time we can probably expect the user to turn the command on or off manually.
> Time Range Restriction

- backend/app-management/electron/events/when-ready.js
- backend/common/effect-runner.js
- backend/database/json-db-manager.js
- backend/effects/builtin/effectGroup.js
- backend/effects/preset-lists/preset-effect-list-manager.js
- backend/effects/queues/effect-queue-manager.js
- backend/import/setups/setup-importer.js
- server/api/v1/controllers/effectsApiController.js
This creates a class which can be extended by manager classes that interact with a json db. It removes and prevents code duplication and centralizes the data interaction. I updated the effect queues and preset effects lists already, but it may be nice to implement it in other parts of the codebase as well.
I tested if all changed functionality still works as it should.
> Create a json db manager class

- backend/restrictions/builtin/time-range.js
This updates the time restriction to allow users to select specific days in addition to a time.
#1493 
- Test day restriction by selecting current day.
- Test day restriction by selecting days other than the current day.
- Test day restriction by doing both of the above, but also selecting multiple days at once.
- Test time restriction by selecting a current time range.
- Test time restriction by selecting a time range outside of the current time.
- Test time restriction by selecting a time range that spans past midnight.
- Test a combination of both by applying two time restrictions to the same command. One for time and one for days.
I'm pretty sure this should be backwards compatible. It defaults to the time mode. However, it might be worth a close look at the code with that in mind.
> #1493 - Add a day selection option to the time range restriction.

- backend/events/builtin/twitchEventSource.js
- backend/events/filters/builtin-filter-loader.js
- backend/events/filters/builtin/chat-mode-duration.js
- backend/events/filters/builtin/chat-mode-setting.js
- backend/events/filters/builtin/chat-mode.js
- backend/events/twitch-events.js
- backend/events/twitch-events/chat-mode-changed.js
- backend/twitch-api/pubsub/pubsub-client.js
- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/chat-mode-duration.js
- backend/variables/builtin/chat-mode.js
- backend/variables/builtin/moderator.js
This adds an event that triggers when a chat mode change has been made. 
I added three filters:
- A chat mode filter with which you can filter Emote Only, Followers, Subscribers Only, Slow, and Unique chat
- A setting filter to check if a chat mode has been enabled or disabled
- A duration filter for slow (seconds) and followers (minutes)
I also added two variables: `$chatMode` and `$chatModeDuration`.
I tested if the event works, including the filters and variables.
> Add a new event for chat mode changes

- backend/integrations/builtin/streamelements/streamelements-event-handler.js
- backend/integrations/builtin/streamelements/streamelements.js
- backend/variables/builtin/donation-amount-formatted.js
It seems the websocket data has changed for actual events (so not the test data): https://dev.streamelements.com/docs/kappa/ZG9jOjYxMzcxNTY-connecting-via-websocket-using-o-auth2
I updated the listener to get the proper data, and I also added a formatter for the amount. The documentations says that `amount` is an Int32, so apparently the amount gets rounded? 
#1029 
I tested the follow event, the donation event is not testable unfortunately since the test functionality provides different data.
> Fix the event listeners for StreamElements and add a formatted amount

- server/api/v1/controllers/effectsApiController.js
Username and args sent via query string are now passed to a preset effect list when API is hit via GET request.
#1613
Created a simple preset effect list that performs TTS using both an arg and the username. Verified that GET requests now use the query string and POST requests are still able to use the request body.
N/A
> Add query param handling for preset effect list GET requests

- backend/chat/chat-helpers.js
Added check for `streamer.displayName` to username tag check for Chat Notification so that it triggers on both names and not only the username.
#1607 
Manually tested that the bot notifies on both variants of the username
> Added displayName to fix #1607

- backend/integrations/builtin/discord/send-discord-message-effect.js
Adds a simple notification that shows up if someone selects Channel Detail embed that the channel has to be live for it to work.
#1639 
Tested to see that it only shows up when Channel Details and not for Custom Embed.
> Adds a notice to Channel Detail embed  #1639

- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/array-find-index.js
This adds a $arrayFindIndex[jsonArray, matcher, propertyPath] variable that extracts the index of the array `jsonArray` where the item matches `matcher`. If `propertyPath` is filled, it tries to match the object item by following the property path. 
If it can't find a match, it returns null. 
#1638 
Created a chat command with the following : 
$arrayFindIndex["[\"a\",\"b\",\"c\"]", b] | 
$arrayFindIndex["[{\"username\": \"alastor\"},{\"username\": \"ebiggz\"}]", alastor, username] || 
$arrayFindIndex["[\"a\",\"b\",\"c\"]", d]  | 
$arrayFindIndex["[{\"username\": \"alastor\"},{\"username\": \"ebiggz\"}]", toto, username]
Checked the return value is "1 | 0 || null | null"
> #1638 add $arrayFindIndex variable

- backend/variables/builtin/custom-variable.js
- backend/variables/builtin/user-metadata.js
Apply recommendations on improving #1648 to customVariable and userMetadata, that have the same issues. 
- Set customVariable `test` to `[{"username":"alastor"}, {"username":"buttastor"}]`
- Output to chat 
> $customVariable[test] | 
> $customVariable[test, 1] | 
> $customVariable[test, 1, defaultValue] || 
> $customVariable[test2] | 
> $customVariable[test, 4] | 
> $customVariable[test, 4, defaultValue]
- Checked that the output is `[{"username":"alastor"},{"username":"buttastor"}] | {"username":"buttastor"} | {"username":"buttastor"} || | | defaultValue`
- Set customVariable `test` to `{ "username" : "alastor", "location" : "pungeon"}`
- Output to chat : 
> $customVariable[test, "username"] | 
> $customVariable[test, "username", defaultValue] || 
> $customVariable[test, "username2"] | …
> Fix customVariable and userMetadata parameters checks

- backend/effects/builtin/log-message.js
Adds a Log Level dropdown that defaults to Info but has all four log levels: Info, Warning, Error, and Debug.
#1669
Created a command with a Log Message effect and tested all 4 log levels. Verified in log file.
> Add log level option to Log Message effect

- backend/variables/builtin/chat-messages.js
Update `$chatMessages` to use `username` parameter instead of always using `triggers.metadata.username`
#1672
Trust me, it works
N/A
> Fix $chatMessages username bug

- backend/effects/builtin/clips.js
Adds an option to the **Create Clip** effect to save the clip URL to a custom variable for use in later effects. Validates that a variable name is entered if the option to save the URL is selected.
#1667
Created a clip via effect, verified data value and timeout.
> Add custom variable option when creating clip

- backend/effects/builtin/http-request.js
Changes the HTTP Request effect to only send body data on POST, PUT, or PATCH requests.
#1664
Verified that POSTs send body and GETs no longer do.
N/A
> Only send HTTP body on POST, PUT, or PATCH

- backend/effects/builtin/log-message.js
- server/api/v1/controllers/commandsApiController.js
- server/api/v1/v1Router.js
Adds the following API endpoints for commands:
`/api/v1/commands/system`
- GET list of all system command IDs, names, and base triggers
`/api/v1/commands/system/:sysCommandId`
- GET full definition for specified system command
`/api/v1/commands/system/:sysCommandId/run`
- GET or POST to run system command. Accepts parameters of `username`, `args`, and (POST only) trigger `metadata` object
`/api/v1/commands/custom`
`/api/v1/commands/custom/:customCommandId`
`/api/v1/commands/custom/:customCommandId/run`
Same as above, but for user-defined custom commands. Note that custom command list returns description instead of name.
**NOTE:** This currently executes a command using the same method call as the **Run Command** effect, so subcommand triggers are not supported, just as in the effect.
N/A …
> Basic Command API endpoints

- server/api/v1/controllers/effectsApiController.js
- server/api/v1/v1Router.js
Adds an API endpoint at `api/v1/effects/preset` to GET all preset effect lists, including ID, name, and a list of arguments they take
N/A
GET-ted the list. Hooray!
N/A
> Get all preset effect lists via API

- backend/app-management/electron/window-management.js
- backend/common/custom-variable-manager.js
- gui/variable-inspector/index.html
- gui/variable-inspector/preload.js
Adds a delete button to permanently remove (i.e. not just expire) a custom variable in the custom variable inspector.
#1680
Created several custom variables, deleted them, closed and reopened inspector window to ensure variables had been deleted and that other variables were intact.
> feat(variables/#1680): add ability to delete variables via inspector

- backend/variables/builtin/top-metadata.js
With assistance of SReject changed the way the query is done so that it filters out any results not containing the key in metadata before it returns the data to the variable-replace function.
Refs: #1686
Created a command with `$topMetadata[lurk, 5]` which only returns the 4 records in the database.
Changed the variable to check for a metadata key not in the database and now it returns `(none)` instead of the variable itself.
> fix: Issues with topMetaData

- backend/database/userDatabase.js
- backend/effects/builtin-effect-loader.js
- backend/effects/builtin/remove-user-metadata.js
Moved the deleteusermetadata function into its own function so it can be used outisde of the frontendCommunicator, and renamed it to removeUserMetadata.
Made the delete-user-metadata frontend call use the removeUserMetadata function.
Added a new effect for removing user metadata as well as added it to the builtin-effect-loader.
Refs: #1688
Added the newly effect to a !unlurk command, which works together with a !lurk command which sets the metadata key lurk for the user running the command, when user types in chat later this triggers !unlurk which then removes the lurk metadata key.
Also tested that the metadata key remove function works from the viewer modal after I rearranged the userDatabase file.
Kind of hard to show that a key got removed, so added a new one while removing the one in …
> Feat: Added a remove user metadata effect

- gui/scss/core/_bootstrap-overrides.scss
Fixed so the dropdown-menu triggered by the meatball menu don't get covered by sticky-bottom "Reward Limit" line by raising the z-index for dropdown-menu.
Refs: #1571
Tested the meatball menu with a limited channel reward list so the limit bar is high up in the UI to force the menu to go lower than the bar in the UI. See screenshots.
Before change:
After change:
> Fix: Adjusted z-index for dropdown-menu

- backend/chat/moderation/chat-moderation-manager.js
- backend/utility.js
- gui/app/controllers/moderation.controller.js
- gui/app/directives/modals/misc/editUrlAllowlistModal.js
- gui/app/directives/modals/misc/txtFileWordImportModal.js
- gui/app/index.html
- gui/app/services/chat-moderation.service.js
- gui/app/templates/_moderation.html
Adds an allowlist feature to URL moderation to automatically permit links that match allowlist rules. Also updated URL regex to match URLs that don't have trailing `/` after domain name (e.g. `https://firebot.app` vs `https://firebot.app/`).
#1564
- Added terms to the URL allowlist one at a time
- Imported terms en masse to the URL allowlist from a text file
- Deleted individual terms from the URL allowlist 
- Deleted entire URL allowlist at once
- Verified URL allowlist DB file saves
- Verified URL allowlist reloads when reopening Firebot
- Tested moderation with alternate account
- Message with single URL that matched a rule allowed
- Message with single URL that did NOT match a rule deleted
- Message with multiple URLs that all matched rules allowed
- Message with multiple URLs where …
> feat: Add URL moderation allowlist

- backend/events/twitch-events/gift-sub.js
This fixes multiple bugs with the change to use chat-based gift sub events (reported in #1662, changed in #1663). Bugs fixed:
- Fix `username` field value to use gifter fields or "Anonymous" when anonymous, as `displayName` corresponds to the recipient, not the gifter.
- Fix `giftSubMonths` to use `months` field as `streak` does not exist on chat sub event.
- Fix `gifterUsername` to fallback to `gifter` instead of `displayName`, as `displayName` corresponds to the recipient, not the gifter.
- Fix `isAnonymous` property to correctly trigger anonymous gifts.
Related to issue #1662/PR #1663.
Gifted a sub to my bot and received the following data back for verification. Verified all fields both from this and also from twurple source.
``` javascript
{
userId: '626526988',
displayName: …
```
> fix: Mutiple bugs with chat-based gift sub event

- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/array-element.js
Adds the `$arrayElement` variable that will return the element at the specified index of a JSON array, given the format `$arrayElement[jsonArray, index]`.
#1627
Created a custom variable that was set using the `$arrayElement` variable around a `$splitText` variable and verified that the array element at the specified index was saved as the custom variable value.
N/A
> feat: add $arrayElement variable

- backend/integrations/builtin/elgato/elgato.js
When a color name (not hex code) is specified for Elgato Light Strip color, the name is now converted to lowercase first in order to properly convert.
N/A
Tested both `blue` and `Blue` to ensure that lights changed to specified color.
N/A
> fix: elg light strip color name case sensitivity

- backend/integrations/builtin/discord/discord-embed-builder.js
- backend/integrations/builtin/discord/send-discord-message-effect.js
Adds the option to embed an image to a Rich Embed Discord message effect.
No issue
Tested with an image URL assigned to the effect and without.
Both works as intended, with an URL it posts the message with the image attached, without an URL it posts without.
Discord Embed Settings:
Output in Discord:
> feat: discord image embed

- backend/effects/builtin/shoutout.js
Added a new text field to the Shoutout effect so that Last Seen Playing text can be customized.
#1691
See screenshots, different text shows different text in the overlay.
Effect Settings:
In action:
In action:
> feat: customizable last seen text

- gui/scss/Light.scss
- gui/scss/Midnight.scss
- gui/scss/Obsidian.scss
- gui/scss/core/_global.scss
Added a variable for changing the color of the palette title depending on theme selection to make it readable with the darker themes.
#1693 
Changed between themes to check that font color changes in the palette and that it is readable.
Obsidian:
Light: 
Midnight:
> fix: color select illegible in dark mode #1693

- backend/integrations/builtin/elgato/effects/update-key-lights.js
- backend/integrations/builtin/elgato/effects/update-light-strips.js
Updated the Elgato light effects to display the "no lights" message when the array exists but has 0 elements.
N/A
Verified that when no lights are found but the integration is working correctly, the "no lights" messages are shown.
> fix: elgato light effects have clearer message

- backend/effects/builtin/stream-game.js
- backend/restrictions/builtin/channel-game.js
- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/category.js
- backend/variables/builtin/game.js
- gui/app/controllers/quotes.controller.js
- gui/app/directives/modals/quotes/addOrEditQuoteModal.js
Added new `category` variable with logic from `game` variable, updated `game` variable to use `category` variable logic to prevent duplicate code, updated several UI locations to change "game" to "category" or "category/game" for clarity & consistency with Twitch nomenclature and to match other places in the UI (e.g. "Category Changed" event).
#1661
Verified UI changes, verified new `category` variable works just like `game`, verified `game` still works as before.
> feat: add category var, refactor usage of "game"

- backend/events/twitch-events/cheer.js
Fall back to "An Anonymous Cheerer" when pubsub provides an undefined `userName`. 
I'm not particular about the spaces in the username, was just trying to mimic the fallback for anonymous gifts of "An Anonymous Gifter"
#1705
Cheered 25 bits both anonymously and non-anonymously. Event was set up with chat message effect with text `$user has cheered $cheerBitsAmount`
Before:
After:
> #1705 Fallback username for anonymous cheers

- backend/effects/builtin/custom-variable.js
Added a menu position override for the Variable Name input field
#1632
After the change has been applied:
See screenshot from before in the following comment:
https://github.com/crowbartools/Firebot/issues/1632#issuecomment-1076380419
> Fix: $vars menu position for custom-variable

- backend/database/currencyDatabase.js
Updates the currency database to allow specifically setting a user's currency value to 0.
#1603
Ensured that currency could be set to 0 via the **Update Currency** effect for a single user, all online users, all users, and all online users in a specific role.
N/A
> fix: allow setting user currency to 0

- backend/effects/builtin/play-video.js
Adjust volume slider to allow volume of 0 (effectively muted) on local video option in **Play Video** effect.
#1714
Played a video with sound in the overlay at volume 0, verified that no audio played. Played another video with higher volume level, verified that audio track played.
> feat: allow local videos to play at 0 volume

- backend/effects/builtin/clear-effects.js
Fix display bug in **Clear Effects** effect where choosing Default overlay when overlay instances are enabled would result in a blank entry.
#1721
Verified that choosing Default overlay now actually displayed "Default" and that clearing the overlay still works.
> fix: clear effects "default" overlay name

- backend/database/currencyDatabase.js
- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/currency-rank.js
Add `currencyRank` variable to determine the given viewer's rank based on the amount of the given currency they have relative to user viewers.
#1626
Verified that a valid user and currency return the given rank, and that both an invalid currency and/or invalid user returns 0.
N/A
> feat: currencyRank variable

- backend/variables/builtin-variable-loader.js
- backend/variables/builtin/regex-matches.js
Add `$regexMatches` variable that returns a JSON array of all regex matches in a string.
Related to #1728
Created a string and an expression and verified that all matches in the string were returned as a JSON array.
N/A
> feat: add $regexMatches variable

- gui/app/directives/modals/chat/chat-settings-modal.js
- gui/scss/core/_chat.scss
- gui/scss/core/_global.scss
Organized chat settings into common groups so that specific settings can be found easier.
This updates the chat settings modal to organize settings into common groups. 
None, this was done in preparation for adding a setting to filter user roles from the chat user list.
- Open firebot
- Open chat modal
- Make sure nothing looks broken.
- Make sure settings can still be toggled and their settings are saved.
> style: organize chat settings into common groups

- backend/chat/chat-listeners/active-user-handler.js
- backend/database/userDatabase.js
- gui/app/directives/chat/chat-user-category.js
- gui/app/directives/modals/viewers/viewerDetailsModal.js
- gui/app/services/chat-messages.service.js
This implements #922. It gives users the ability to hide usernames from the viewer list that sits next to chat. This can be toggled on per user via the user modal.
When the setting is updated, the viewer will remain on the viewer list until the next time that viewer list refresh event occurs, at which time they will be filtered out.
#922 
- Connect firebot and let users show in the userlist.
- Click a username (preferably a persistent bot account) to open their modal.
- Click the new hide from viewer list option.
- Close the modal.
- Wait until the next chat refresh happens, and observe that the username disappears.
- Go into the viewer database and find the name again.
- Click it to open the viewer modal.
- Deselect the new option.
- Go back to chat and wait for the refresh, then observe …
> feat: ability to filter users from the viewer list

- gui/app/directives/chat/feed items/chat-message.js
Links in chat in the Dashboard now honor the custom chat text size
N/A
Verified link text is now the same size as other text.
> fix: chat links now use custom chat text size

- gui/app/controllers/commands.controller.js
When copying a command, we now reassign the correct `fallback-subcommand` ID to the fallback of the copy so that fallbacks will execute properly.
#1759
Copied a command and verified that fallback subcommand worked immediately after copy without need to delete/recreate fallback subcommand.
N/A
> fix: copied commands no longer assign bad fallback subcmd id

- backend/effects/builtin/currency.js
Add the `$vars` button to the Update Currency effect's chat message box.
#1753
Verified `$vars` button displays and functions in UI.
> fix: add $vars to Update Currency chat message box

- backend/chat/commands/builtin/commandManagement.js
Adds the `!command addalias` and `!command removealias` subcommands for alias management.
#1751
- Verified that `addalias` adds the specified alias to a custom command
- Verified that `removealiash` removes the specified alias from a custom command
- Verified that `addalias` does NOT add an alias that already exists on a custom command
- Verified that `removealias` does NOT attempt to remove an alias that does not currently exist on a custom command
> feat: !command addalias/removealias subcommands

- backend/chat/chat-listeners/active-user-handler.js
Made sure that userDetails has the correct casing for username by applying .toLowerCase().
#1771 
Tested to make sure that the streamer shows up with the active user role as well as with the correct casing in viewer list, chat feed.
Tested with setting for disabling active user disabled:
Tested with setting for disabling active user enabled:
> fix: Active User Role for streamer account (#1771)

- backend/effects/builtin/conditional-effects/conditions/builtin/custom.js
Adds `is strictly` and `is not strictly` comparison types to the conditional effect custom conditions.
N/A
Verified that `0` and `""` are not treated equally with `is strictly` comparison.
Verified that `0` and `""` are still treated as equal with `is` comparison.
N/A
> feat: "strictly" custom effect conditions

- backend/events/twitch-events/gift-sub.js
Change the condition on the community gift sub event to properly reflect the status of the sub being anonymous or not.
#1796
Regression from https://github.com/crowbartools/Firebot/pull/1663
To reproduce: gift a non-anonymous community sub from Twitch. **You can not reproduce this without Twitch chat events.**
I was unable to test the fix due to testing requiring the usage of real Twitch events, but logic dictates this should fix the issue.
N/A
> fix: Anonymous community sub detection in event

- backend/common/handlers/fileWriterProcessor.js
Split on `\n` and remove `\r`. 
The issue is that a file with `\r\n` (`0D 0A`) as the EOL,
sent from a windows os will not replace the text while Splitting on just `\n`.
the text will retain the 0D of the EOL `\r`.
.Trim() would have been another option but Space and Tab at
the end of a line would cause the same problem.
if the user is expecting a space and its removed then it wont delete
the line, same with tab.
This PR should resolve issue #1790
#1790
```
63 68 65 73 74 0D 0A 68 61 6E 64 0D 0A 61 72 6D            chest..hand..arm
0D 0A 6E 65 63 6B 0D 0A 68 65 61 64 0D 0A 6C 65            ..neck..head..le
67 0D 0A 66 6F 6F 74 0D 0A 6B 6E 65 65 0D 0A 73            g..foot..knee..s
68 6F 75 6C 64 65 72 0D 0A 74 68 69 67 68 0D 0A            houlder..thigh..
66 69 6E 67 65 72 73 0D 0A 65 61 …
```
> Fix: write to file delete by text #1790

- backend/twitch-api/resource/users.js
Return userFollow != null;
will return true or false based on if userFollow is null
It simply evaluates the expression.
If userFollow is null it returns false
if userFollow isn't null, it returns true.
this is not if the value form twitch is true or false or null
#1799
> Fix: userFollow restriction

- backend/games/builtin/slots/slots.js
Updated the default maxWager message in the Slots game to read correctly, similar to the same message for other games
N/A
N/A
N/A
> fix: clarify default slots maxWager message

- backend/effects/builtin/run-program.js
Adds an "All Files" option to the Run Program effect's browse dialog. This will be especially useful for Linux users, where executables don't typically use Windows extensions.
#1826
Verified that the Run Program browse dialog shows both the original "Programs" and the new "All Files" options.
N/A
> feat: add All Files to Run Program browse dialog (#1826)

- backend/common/handlers/custom-scripts/script-types.d.ts
- backend/effects/builtin/clips.js
- resources/overlay/js/main.js
Adds dynamic URL support for overlays, including support for Twitch clips.
NOTE: Twitch clips require HTTPS for anything that isn't `localhost`. Also, local media will NOT play over a remote overlay URL.
N/A
Created a localtunnel instance pointing to my default Firebot web server running on `http://localhost:7472`. Loaded the localtunnel URL from another device and send a Twitch clip to the overlay, which played as expected on the remote device.
N/A
> feat: dynamic overlay URL support

- backend/backupManager.js
- backend/common/settings-access.js
- gui/app/directives/settings/categories/backups-settings.js
- gui/app/services/settings.service.js
Add an option to not include the overlay-resources folder in the automatic backups.
Reason for this is:
I have been heavily using the overlay-resources folder for my rescoreses on my overlays and overlay instances. I keep a separate dev folder on a separate drive. over time this folder has become maybe 3 gig in size. this is due to images and textures and sound bits and models. it would be nice to be able to turn off backing this folder up or moveing it out of the root of firebot all together and asigninging within firebot. so i can point at my dev folder. when i exit firebot it takes a good bit maybe 10 min to a half hour to fully shut down because of all the assets that are in that folder.
due to CORS errors in the overlay scripts all assets have to be within the webserver folder …
> feat: Add an option to not include the overlay-resources folder in the automatic backups.

- backend/effects/builtin/cooldown-command.js
moved the Cooldown base command radio buttons down so they are not on top of the dropdown selection
by changing from margin-bottom to margin-top 
#1770 
before 
after
> feat: Cooldown command radio buttons in the wrong place #1770

- backend/twitch-api/resource/channels.js
Updates a deprecated Twurple call to get channel info
#1802
Verified that channel info is still able to be queried using new call (`$category` variable used to test)
N/A
> fix: update deprecated Twurple call

- backend/effects/builtin/clips.js
- backend/effects/builtin/play-video.js
Adds volume support to Twitch clips played in overlay. Also rewrites Twitch clips in the overlay to play the raw video URL in a `<video>` element instead of a Twitch player embedded in an `<iframe>`.
**NOTE:** Users may have to adjust volume settings for any **Play Video** effects they have that are set to either **Twitch Clip** or **Random Twitch Clip**, as they will now play at the effect's default volume of 50%, whereas before they were all playing at 100%.
#1833
Verified that both specific and random Twitch clips play in the overlay at the specified volume.
> feat: add volume support for Twitch clips

- backend/database/currencyDatabase.js
Added a null check for user `twitchRoles` when adding currency to all online users in a group.
#1832
N/A
N/A
> fix: null twitchRoles in currency add

- backend/app-management/electron/window-management.js
Adds new **File** menu and reorganizes some options under the new menu. Also adds **Import Firebot Setup...** option to new menu.
N/A
Verified new menu option works correctly and all moved menu options still work as before.
> feat: new FIle menu, reorg other menus

- src/server/http-server-manager.js
Fixes a bug with custom route registration in HttpServerManager. Previously, it would not allow custom routes with the same name but different verbs.
N/A
Verified that custom routes with the same name could be registered with different verbs (e.g. GET, POST, DELETE).
N/A
> fix: HttpServerManager custom route registration

- src/backend/auth/twitch-auth.js
- src/backend/chat/twitch-chat.js
- src/backend/twitch-api/api.js
- src/backend/twitch-api/resource/whispers.ts
Sending whispers now uses the new REST API endpoint. NOTE: This will require users to reauthenticate to Twitch.
N/A
Verified sending whispers works using new endpoint
N/A
> feat: update whispers to use new API endpoint

- src/backend/chat/moderation/chat-moderation-manager.js
- src/backend/chat/moderation/moderation-service.js
- src/gui/app/directives/modals/misc/editBannedWordsModal.js
Adds additional verification around banned RegEx adding and checking to prevent moderation service from crashing.
N/A
Verified that invalid RegEx can no longer be added via moderation Edit Banned Words dialog. Verified existing invalid RegEx is skipped and does not crash moderation service.
N/A
> fix: banned RegEx validation

- src/backend/utility.js
**Issue:**
Currently the bot's allowlist for URL moderation doesn't work for the path component of a domain. I'd like to also filter not just on the domain, but also path part. For example for multistreams I'd love to allow the urls to the channels of my costreamers only, but not all twitch links in general.
For example allowing just `https://twitch.tv/good_streamer` won't work since the current regex only picks up the `https://twitch.tv/` part and everything after gets ignored.
leaving me the choice to whitelist twitch as a whole or not at all.
**Fix:**
Changing
```js
const getUrlRegex = () => {
return /\b(?:https?:(?:\/\/)?)?(?:[a-z\d](?:[a-z\d-]{0,253}[a-z\d])?\.)+[a-z][a-z\d-]{0,60}[a-z\d](?:$|[\\/]|\w?)/gi;
};
```
and adding a single `+` to the last group will make the path component …
> feat: make the URL allowlist discern on the path component of a URL

- src/backend/integrations/builtin/aws/text-to-speech-polly-effect.js
Introduce 2 fixes for Amazon Polly SSML.
Introduce `<speak></speak>` when SSML is selected, fixes some SSML tags not working.
Escape `&` character to make it work in an SSML message.
Note: a fix for the `<` character is NOT included, more work needs to be put into filtering so genuine SSML tags aren't escaped/encoded
#1866 
When testing the fix, every example text in the reproduction steps, except for the one with a `<` character now works. See the note above for clarification.
N/A
Thanks to @Nikoheartttv (Nikoheart#0001) for helping with this issue.
> fix: resolve some SSML issues with Amazon Polly

- src/backend/integrations/builtin/streamloots/filters/chest-gift.js
Fixed the logic for the the selection of the "A Gift" "Not A Gift" on the streamloots chest event 
#1871
Tested using the simulate event to create chest purchase of a gift and non gift chest 
this is now working as intended.
> fix: streamloots chest is a gift and is not a gift streamloots chest event #1872

- package-lock.json
- package.json
- src/server/api/v1/controllers/countersApiController.ts
- src/server/api/v1/controllers/customRolesApiController.ts
- src/server/api/v1/controllers/timersApiController.ts
- src/server/api/v1/controllers/viewersApiController.js
- src/server/api/v1/v1Router.js
Adds the following API endpoints:
`GET /customRoles` - Lists a summary of all custom roles (`id`, `name`, `viewers`)
`GET /customRoles/:customRoleId` - Get info about a specific custom role
`POST /customRoles/:customRoleId/viewer/:userId` - Adds the specified user to the specified custom role. Can specify user ID, or username with `username=true` query parameter
`DELETE /customRoles/:customRoleId/viewer/:userId` - Removes the specified user from the specified custom role. Can specify user ID, or username with `username=true` query parameter
Also added corresponding viewer endpoints:
`GET /viewers/:userId/customRoles` - Lists all custom roles for the specified user
`POST /viewers/:userId/customRoles/:customRoleId` - same as `POST /customRoles/:customRoleId/viewer/:userId`
`DELETE …
> feat(api): custom role mgmt, counters, timers

- src/backend/integrations/builtin/aws/text-to-speech-polly-effect.js
- src/gui/app/services/sound.service.js
Added a maximum duration parameter to help curb overly long winded Polly and native TTS messages. 
https://github.com/crowbartools/Firebot/issues/1797
- Added new chat !command trigger
- Added Polly TTS effect
- Set text to the Shungite copypasta (it takes about 30 seconds for built-in TTS to read)
- Did not set new maximum duration property
- Tested event. Observed that the whole message was read out
- Edited event and set maximum duration to 7 seconds
- Tested event. Observed that only the first 7 seconds were read, approximately one sentence
- Edited event again and set maximum duration to -1
- Tested event. Observed that the whole message was read out
Repeated the above tests but with the built-in text to speech effect instead of Polly
> #1797 Add time limit to Polly and native TTS

- src/backend/app-management/electron/window-management.js
- src/gui/app/app-main.js
Adds a **Restore from backup...** option to the **Tools** menu, with a confirmation modal.
N/A
Restored backup from new menu option
> feat: Restore from backup in Tools menu

- src/gui/app/services/updates.service.js
Auto update no longer runs in dev environments or non-Windows OSes.
#1824, #1825
Verified that auto-updates do not attempt to run for dev builds, but still run for packaged builds.
N/A
> feat: prevent dev/non-Windows auto-updates

- src/backend/events/EventManager.js
- src/gui/app/directives/modals/events/simulateGroupEventsModal.js
Add a new option to the Simulate Event dialog to force an event to run, even if a similar event was recently run and is in the cache.
#1782
Verified simulated events will bypass cache when new option is selected, but still honor cache when it is NOT selected (default behavior).
> feat: allow simulated events to force run

- src/backend/effects/builtin/celebration.js
- src/backend/effects/builtin/play-sound.js
- src/backend/effects/builtin/play-video.js
- src/backend/effects/builtin/shoutout.js
- src/resources/overlay/js/util.js
Overlay elements now use UUIDs instead of the current time to uniquely name elements
#1600
Verified that overlay elements now generate UUIDs for IDs instead of timestamps
N/A
> feat: overlay elements now use uuid

- .vscode/launch.json
- .vscode/tasks.json
Add `grunt prep` task to VSCode debug launch
N/A
Verified `grunt prep` runs when starting debugging
N/A
> chore: add grunt prep debug prelaunch task

- src/backend/common/effect-runner.js
- src/backend/effects/builtin/conditional-effects/conditional-effects.js
- src/backend/effects/builtin/effect-group.js
- src/backend/effects/builtin/http-request.js
- src/backend/effects/builtin/random-effect.js
- src/gui/app/directives/controls/firebot-checkbox.js
- Adds option to have effect outputs be applied to parent lists (run effect list, random effect, and conditional effects)
- Update HTTP Request effect to use outputs
> feat: allow effect outputs to be bubbled to parent lists, update http request effect to use outputs

- src/backend/integrations/builtin/obs/obs-integration.ts
- src/backend/integrations/builtin/obs/obs-remote.ts
- src/backend/integrations/builtin/obs/variables/is-recording.ts
- src/backend/integrations/builtin/obs/variables/is-streaming.ts
- src/backend/integrations/builtin/obs/variables/stream-is-running.ts
Adds new `$obsIsStreaming` and `$obsIsRecording` variables. They return 'true' if OBS is currently streaming/recording and 'false' if it isn't.
N/A
Verified variables returns correct values.
N/A
> feat: $obsIsStreaming and $obsIsRecording variables

- src/backend/integrations/builtin/obs/obs-remote.ts
Adds Linux support for the **Set OBS Source Text** effect.
#2032
Verified this still works on Windows. Linux testing to be completed by @dennisrijsdijk.
N/A
> feat: Linux OBS text source update

- src/backend/auth/twitch-auth.js
- src/backend/twitch-api/chatter-poll.ts
- src/backend/twitch-api/resource/chat.ts
Refactor the online chatter poll to be in TS, use official Twitch chatters API instead of deprecated unofficial endpoint.
N/A
Validated both initial load and refresh.
N/A
> chore: refactor chatter poll, use official API

- src/backend/effects/builtin/file-writer.js
- src/backend/integrations/builtin/obs/effects/set-obs-source-text.ts
This PR enables larger multi-line textboxes on the **Text** and **Replacement Text** inputs for the **Write To File** effect, as well as the input for **Set OBS Source Text**
N/A
I've tested and verified that text is still properly written to file (with multiline/newline support) and that previously created effects still work properly.
For the OBS Source Text, I've tested that text properly gets set on the text source (with multiline/newline support) and that previously created effects still work properly.
N/A
> fix: Enable use-text-area on relevant textboxes

- src/backend/effects/builtin/play-video.js
- src/resources/overlay/js/main.js
Resource token length for videos is now dynamically fetched from the overlay instead of relying on being set as video duration by the user.
#2058 
I've tested to make sure that there's no noticeable delay on video start, and the video would complete fully.
N/A
> fix: long videos resourceToken expires before video finish

- src/backend/integrations/builtin/obs/effects/save-replay-buffer.ts
- src/backend/integrations/builtin/obs/obs-integration.ts
- src/backend/integrations/builtin/obs/obs-remote.ts
Adds new Save OBS Replay Buffer effect
#1955
Verified replay buffer saved when enabled and active in OBS
> feat: OBS Save Replay Buffer effect (#1955)

- src/backend/variables/builtin-variable-loader.js
- src/backend/variables/builtin/discord-timestamp.js
This adds in a new variable that generates discord timestamps. This is meant to really only ever be used with the "send discord message" effect.  This will generate text similar to "<t:1543392060:R>". It supports all of the formats that discord supports. I've also tried to make it flexible as possible so that people can use it to announce stream times and other things.
- Can exclude the date to use the current date at the specified time.
- Can use 'now' instead of a time to use the current date and time. This allows people to use the current time in whatever format they want.
- Can use any discord timestamp format.
https://discord.com/developers/docs/reference#message-formatting-timestamp-styles
- No issues, but it is important to note that discord will change the output format based on …
> feat: Discord Timestamps Variable

- src/backend/auth/twitch-auth.js
- src/gui/app/app-main.js
- src/gui/app/index.html
- src/gui/app/services/connection.service.js
Auto logout Twitch accounts that are out of date (missing OAuth scopes, has legacy `refresh_token`)
N/A
Verified valid accounts do not logout, and out of date accounts both logout and show the Manage Logins dialog with the applicable messaging.
> feat: auto logout for outdated Twitch accounts

- src/backend/effects/builtin/loop-effects.js
changes the loop initialization of count to string to prevent the trim() error 
#2165
i tested both loop count and loop conditional by creating a new loop and by changing the loop count
> fix: Loopeffects being initialized as int but expecting string

- src/backend/effects/queues/effect-queue-manager.js
Add null-checking for effectQueueManager.getItem as effectRunner still requests null queues.
> fix: null/undefined itemId for queue manager

- src/backend/effects/builtin/play-video.js
- src/gui/app/services/video.service.js
Fixes Youtube Video duration fetching. Youtube may reject requests to load the video, which means we can't fetch the duration. If this happened previously, the youtube video would load in the overlay (and sometimes succeed to play) while the backend would wait for 0 seconds. This could create situations where multiple videos would play, or setups would otherwise break.
With these changes, if the video effect is set to wait and there's an error retrieving the video duration, the effect logs an error message and stops without playing the video. If the effect is not set to wait, it'll continue to send the youtube video to the overlay. During testing, Youtube was more likely to block the iframe API in electron than the iframe API in the overlay, so this can help some videos to still play.
N/A …
> Youtube Video Fix

- src/backend/chat/commands/builtin/quotes.js
- src/backend/variables/builtin/quote-as-object.js
- src/backend/variables/builtin/quote-as-raw-object.js
- src/backend/variables/builtin/quote.js
Updated quotes to use "Quote Date Format" setting.
#1954
!quote command and $quote, $quoteAsObject and $rawQuoteAsObject were tested before and after the change. before, they all returned MM/DD/YYYY regardless of setting. Now, they all follow the setting. When the setting is changed, the output is the new format.
> Quotes: Use "Quote Date Format" setting for date output.

- src/backend/effects/queues/effect-queue-manager.js
Move null check in queue manager to catch both invalid and null queue IDs.
N/A
Ensured that both null (never assigned a queue) and invalid (queue assigned, later deleted) queue IDs return null instead of trying to create a queue object.
> Queues: Move null check, fixes invalid queue ID causing error

- src/backend/effects/builtin/play-video.js
- Fix issue with youtube videos not passing properties properly when wait is disabled.
- Fix issue with user entered video duration being overwritten by resolved duration from duration check.
N/A
Testing done by CKY, looking for more testing from affected users in Discord
> fix: video duration regression

- src/backend/integrations/builtin/aws/text-to-speech-polly-effect.js
Add null check for lexicons when running AWS Polly effect
#2244 
Ensured that effects without the lexicons property still play.
> fix: amazon polly effects from before update not working

- src/backend/chat/chat-listeners/twitch-chat-listeners.js
- src/backend/chat/commands/command-executor.js
- src/backend/database/userDatabase.js
- src/backend/events/twitch-events/announcement.ts
- src/backend/events/twitch-events/chat-message.ts
- src/backend/events/twitch-events/cheer.ts
- src/backend/events/twitch-events/gift-sub.ts
- src/backend/events/twitch-events/raid.ts
- src/backend/events/twitch-events/reward-redemption.ts
- src/backend/events/twitch-events/sub.ts
- src/backend/events/twitch-events/viewer-arrived.ts
- src/backend/twitch-api/pubsub/pubsub-client.js
- src/backend/variables/builtin/user-id.js
These changes make $userId and $useridname pull data from more events where applicable.
Additionally, this PR supersedes #2258 to also add the userId into the event trigger when a multi-month gifted resub happens.
#1819 
Ensured that an existing setup using these variables doesn't break. In some cases, functionality is more reliable than it was before this PR.
Tested that Multi-Month Gifted Resub fix only triggers on Multi-Month Gifted Resubs, and not on regular resubs.
> fix userid and useridname variables & fix multi-month gifted subscription 

- .vscode/launch.json
- grunt/pack.js
- src/backend/app-management/electron/electron-events.js
- src/backend/app-management/electron/events/open-url.js
- src/backend/app-management/electron/events/second-instance.js
- src/gui/app/services/utility.service.js
- src/main.js
Adds support for the `firebot://` custom URI scheme. The initial hander implements the following URLs:
- `firebot://viewer-card/name/:username` - displays the viewer card for a given Twitch username
- `firebot://viewer-card/id/:userId` - displays the viewer card for a given Twitch user ID
N/A
Validated URI handler works in Windows in both a dev environment and installed in a sandbox
N/A
> feat: add firebot:// custom URI scheme, viewer-card endpoints

- src/gui/app/services/sound.service.js
This PR moves the load and loaderror event listeners into the Howl constructor, mitigating audio caching issues that cause the sound to load before we can subscribe to the event listener.
#2287
Running the same test on both builds, I confirm the issue only happens pre-changes.
> Fix Howler issue related to caching for getSoundDuration (#2287)

- src/backend/events/filters/filter-manager.js
Fixes an issue with events where events would not trigger if set to **any filter passes** and no filters were set.
#2306 
Ensured that both **any filter passes** and **all filters pass** now work properly when no filters are set. Also ensured that both options still handle filters appropriately.
> fix(events): Any filter not triggering with no filters. (#2306)

- src/gui/app/directives/modals/integrations/addOrEditDiscordWebhookModal.js
Changed the RegEx to allow for Canary/PTB Discord and Guilded WebHooks
#2314 
Tested with Discord Canary Webhook URL's and Guilded URL's.
> Fix: Discord Webhook (#2314)

- src/backend/effects/builtin/add-quote.js
- src/backend/effects/builtin/delay.js
- src/backend/effects/builtin/dice.js
- src/backend/effects/builtin/log-message.js
- src/backend/effects/builtin/twitch/create-poll.ts
- src/backend/effects/builtin/twitch/create-prediction.ts
- src/backend/effects/builtin/twitch/create-stream-marker.ts
- src/backend/integrations/builtin/obs/effects/toggle-obs-source-muted.ts
Move multiple clipping variable fields to under and remove unneeded variables button from filter in OBS Source Mute effect
#2313
Ensured variable menus no longer clip, and variables button is removed from OBS Source Mute
> fix(effects): move clipping variable fields

- src/backend/common/effect-runner.js
- src/backend/effects/builtin/conditional-effects/conditional-effects.js
- src/backend/effects/builtin/effect-group.js
- src/backend/effects/builtin/http-request.js
- src/backend/effects/builtin/loop-effects.js
- src/backend/effects/builtin/random-effect.js
- src/backend/effects/builtin/sequential-effect.js
Effect outputs now bubble down into nested effect lists, including the **Run Effect List**, **Loop Effects**, **Run Random Effect**, and **Run Sequential Effect** effects.
#2273
Verified effect outputs bubbled down into a nested effect list via **Run Effect List** and that loops in **Loop Effects** persisted outputs between runs
N/A
> fix(effects): effect outputs now bubble down into nested effect lists (#2273)

- src/backend/app-management/electron/events/will-quit.ts
- src/backend/events/builtin/firebot-event-source.js
Feature Implementation:
Added a new event for when firebot is closed
#2332
tested it with a https request effect
> #2332 [Feature Request] on close/exit event

- src/backend/variables/builtin/user/pronouns.ts
Pronoun variable would return blank on fallback and unknown user
#2373
tested with my account and my bot account that has no pronoun
everything as documented supplies the expected data
$pronouns[username, 0, they/them]
Returns 'she/her' if available, otherwise uses they/them.
$pronouns[username, 1, they]
Returns 'she' pronoun in she/her set if available, otherwise uses they.
$pronouns[username, 2, them]
Returns 'her' pronoun in she/her set if available, otherwise uses them.
> Fix: pronouns to return fallbacks correctly

- src/backend/chat/twitch-chat.ts
allow for updating the ui when re-connected to outgoing chat 
updated the error messages to see what side of the connection is struggling 
#2423
have ran this for 1 hour without the alert staying 
before that the only way to get the alert to remove itself was to restart
> fix:missing autodisconnect #2423

- src/backend/common/user-access.js
- src/backend/restrictions/builtin/follow-check.js
- src/backend/twitch-api/resource/users.ts
- src/gui/app/directives/controls/time-input.js
- src/gui/app/directives/modals/channel-rewards/add-edit-channel-reward.js
Adds the ability to check for the streamer's channel in the Follow restriction
Adds the ability to check for a certain follow age in the Follow restriction
#1193
#2453
Ensured the following:
- Updated UI for restriction works in commands and channel rewards
- A warning is now shown when custom follow check is used regarding the streamer/mod restriction from Twitch.
- By default, Custom follow check is selected.
- Commands and Channel Rewards will successfully reject their triggers when either the follow isn't met, or a follow restriction isn't met
- Both will fail gracefully (reject) if the Custom option is chosen, and a channel is entered that the streamer is not a moderator for
- Both will fail gracefully when an invalid username is entered into the Custom field
- Channel rewards will …
> Follow Restriction Improvements

- src/gui/app/directives/controls/firebot-checkbox.js
- src/gui/app/directives/misc/firebot-item-table/firebot-item-table.html
- src/gui/app/directives/misc/firebot-item-table/firebot-item-table.js
- src/gui/app/directives/misc/tooltip.js
- src/gui/app/templates/chat/_commands.html
- src/gui/scss/core/_firebot-item-table.scss
- src/gui/scss/core/_helpers.scss
- Moves the new "Search full text" option into a popover 
- Removes "search field" option of the item table as it has now been superseded (and likely was bugged)
<br>
<br>
> feat: implement item table advanced search options popover

- src/gui/app/directives/effect-option-settings/eosEnterExitAnimations.js
the enter duration would allow for 0.25 where the rest of the durations would enforce a min of 1 second 
this enforces a min of 1 second 
if less then 1 second is needed there is a millisecond setting 
#2509
i have tested this by creating a show image effect and setting the enter, in-between and exit animation times to less than 1 second
the durations are then all changed to 1 second
> fix: show image duration

- src/backend/events/filters/builtin/reward.js
title got moved at some point to reward.twitchData.title 
updated to reflect this 
also fixed linting 
#2491
> fix: reward filters not having display names

- src/backend/effects/builtin/run-command.js
ensure effect.args is not undefined/null if it is change it to string empty
#2503
ran command effect and undefined was not returned
> fix: runCommand Effect arg returning undefined

- src/backend/variables/builtin/twitch/chat/message/chat-message-text-only.ts
- src/backend/variables/builtin/twitch/chat/message/index.ts
Adds a `$chatMessageTextOnly` variable to get solely the text component of Twitch chat messages. This will trim `link` (URLs), `third-party-emote`, `emote`, and `cheer` message subparts from `$chatMessage`, returning only the plain-text of the message concatenated with spaces. This is suitable for use as a variable for Text-To-Speech input, amongst others, trimming out noisy portions of messages.
#1640 
Despite seemingly being unable to get fontawesome configured appropriately, and having a massively broken user interface in my development environment, verified that numerous messages containing various subsets of words, emotes, third-party emotes, URLs, and the like all were filtered out appropriately through Twitch chat.
> Feat: Add $chatMessageTextOnly variable

- src/backend/effects/queues/effect-queue-manager.js
- src/backend/variables/builtin/utility/get-effect-queue-length.ts
- src/backend/variables/builtin/utility/index.ts
I've added a new text variable "effectQueueLength" as a utility variable. This variable takes in a queue name 
#2513
- Setup a new effect queue call it "testing" make it whatever queue mode you like
- disable the effect queue
- Setup a command and call it !addtoqueue with an effect of Chat that says "hi"
- In the !addtoqueue command set the queue to be "testing" 
- Setup a command and call it !queuelength with an effect of Chat that says "$effectQueueLength[testing]"
- Setup one more command and call it !badqueue with an effect of Chat that says "$effectQueueLength[not-a-real-queue]"
- Now head to the dashboard 
- send a message of "!addtoqueue" which will bring the queue count to 1
- send a message of "!queuelength" it should return a queue length of 1
- send a message of "!addtoqueue" 3 …
> Feat: Add $effectQueueLength variable

- src/backend/app-management/electron/window-management.js
Resets BrowserWindow bounds immediately after creation to accommodate display scaling scenarios.
Fixes #2569
See also https://github.com/mawie81/electron-window-state/issues/80 (hat-tip [SslTomH](https://github.com/SslTomH))
Tested in Win32 on multiple monitors, including negative of the primary monitor in both X and Y directions, in both maximized and windowed states. Tested over multiple scaling values, including non-scaled.
Solution would still ideally need to be confirmed non-breaking for OS-X and Linux, but it's hard to imagine it would be.
Short two-minute video of existing behavior, then application of these changes, followed by a glimpse of the Windows display settings while it recompiles, followed by the new behavior: https://www.youtube.com/watch?v=L3uRZ8vMTj4
> Fix: windows resize with display scaling

- src/server/api/v1/v1Router.js
Changed from using req.headers.host to using req.socket.remoteAddress
#2519 
- Start firebot on this branch
- open the developer tools (you can also see this log in the terminal you started firebot from)
- make a request from another device to ${your_devices_local_ip}:7472/api/v1/status
- verify the logging is using the ip of the second device and not the device firebot is running on
- log should look like:  info: API Request from: 192.168.1.65, for path: /api/v1/status
> Fix: Log requestor ip for api calls

- src/gui/app/directives/modals/setups/import-setup-modal.js
Adjusts the styling of the firebotsetup import dialogs. The use of the `effect-list` class is *not* ideal here, but seems a better solution than a hard-coded color, or the addition of new .scss definitions, which is at the edge of my comfort zone.
None found
Ran through with a few meaningless examples, and validated all application themes and Windows coloring schemes. Ideally, this still needs to be tested on BSD/OS-X/*nix to validate the L143 change, but I can't imagine that I made it any worse.
**Before**:
*note* that the text in the Popout Description dialog is in-fact there and selectable, but it is rendered with white text on a white background in Windows.
**After**:
> Fix: Setup import dialog styling issues

- src/backend/variables/builtin/twitch/chat/message/chat-message-text-only.ts
- src/backend/variables/builtin/twitch/chat/message/index.ts
Adds a `$chatMessageTextOnly` variable to get solely the text component of Twitch chat messages. This will trim `link` (URLs), `third-party-emote`, `emote`, and `cheer` message subparts from `$chatMessage`, returning only the plain-text of the message concatenated with spaces. This is suitable for use as a variable for Text-To-Speech input, amongst others, trimming out noisy portions of messages.
This is a correction of PR #2553 that was accidentally targeted against master instead of v5, with *another* apology to @SReject for the troubles that I caused.
#1640
Verified that numerous messages containing various subsets of words, emotes, third-party emotes, URLs, and the like all were filtered out appropriately through Twitch chat.
> Feat: Add $chatMessageTextOnly variable (attempt 2)

- src/backend/integrations/builtin/obs/effects/set-obs-browser-source-url.ts
- src/backend/integrations/builtin/obs/effects/set-obs-color-source-color.ts
- src/backend/integrations/builtin/obs/effects/set-obs-image-source-file.ts
- src/backend/integrations/builtin/obs/effects/set-obs-media-source-file.ts
- src/backend/integrations/builtin/obs/effects/set-obs-source-text.ts
Adds padding to five obs-set-* effects (`[ "obs-set-media-source-file", "obs-set-source-text", "obs-set-image-source-file", "obs-set-color-source-color", "obs-set-browser-source-url" ]`) that were lacking it.
Corrects #2580
"Yes."
Before (*top*) and afters (*bottom*):
> Fix: Several OBS Source Effects Lacked Padding

- src/backend/variables/builtin/utility/file-read.ts
`$readFile[file.txt, first]` reads the *first* line of the file, **not** the *last* line.
#2574
Nope.
See linked issue for a before screenshot, here's the after (with post-production highlighting in red):
> Fix: Confusing readFile Example Description

- src/gui/app/index.html
made the test effect button on the effect modal accessible with tab
made the effect menu button on the effect modal accessible  with tab 
fixing not screen readers not being able to see the buttons.
#2600
used NVDA screen reader to tell me what element i was tabbing into
> fix: Effect Modal Test Effect Aria accessibility

- src/backend/viewers/viewer-database.ts
With the refactor  of username earlier in the year this endpoint was missed. This was returning the displayName as the username / login name on the API.  This change may break integrations / projects that use the `api/v1/viewers` endpoint where it now will show the login name instead. So this now return the id, username and displayName to still allow integrations / projects  to adapt and show ether the displayName or username / login name.
Related: #2432
> fix: `api/v1/viewers` to return proper username and displayName

- src/backend/integrations/builtin/obs/constants.ts
- src/backend/integrations/builtin/obs/events/obs-event-source.ts
- src/backend/integrations/builtin/obs/obs-remote.ts
Little followup to the `obsIsConnected` Replace Variable, would like to be able to do Housekeeping on some sources/text when I first start up OBS and Disconnected is just good for keeping tabs on things
n/a
Deployed locally and both events fired as expected
https://github.com/user-attachments/assets/0e22a576-29c1-4bd8-8671-da21a3bbf87f
> Feat: `OBS Connected` and `OBS Disconnected` Events

- src/backend/variables/builtin/user/user-avatar-url.ts
- src/gui/app/directives/controls/effectList.js
This adds a new option to the dropdown that has `Copy All Effects`, `Delete All Effects`, etc., that allows you to easily add a group of Effects to a new Preset Effect List, and instantly add it in a Run Effect List effect
#2624
#2530 (kinda, solves the underlying issue but does not implement the requested Effect)
Tested the new option both with Submitting the created Preset Effect List and cancelling, both with expected behavior
https://github.com/user-attachments/assets/bda5dcf8-7260-43ae-9f72-59c2c9ef5151
> Feat: `Convert to Preset Effects List` in Effect list dropdown

- src/gui/app/directives/modals/setups/firebot-component-list-modal.js
- Fix the Export Setup Component dialog filtering. 
- Angular will negate filters that start with an exclamation mark, which is cool. However, many commands start with an exclamation mark, so that negation behavior is undesired here.
- This completely removes any leading exclamation marks from the filtering.
- Cleaned up a trivial arrow-parens lint warning.
None applicable
Tried a number of things to break it, but I think even this one will get past CK.
Screenshot showing searching for (in clockwise order):
- Nothing
- Previously-negated text
- Group/Sorting tags
- Identifiers
> fix: Export Setup Components Filter Negation

- src/backend/effects/builtin/effect-group.js
adds title to the searchable combo
changes the name of Custom to Custom Effect List 
changed the name of Preset to Preset Effect List 
so that screen readers can know that Selected: Custom Effect List is selected. or Preset Effect List is selected 
#2617
i have used NVDA to verify what is being read out is what is displayed on the screen
> feat: Update preset effect list aria item

- src/backend/variables/builtin/misc/index.ts
- src/backend/variables/builtin/misc/unix-timestamp.ts
Implements a `$unixTimestamp` Replace Variable for efficient comparison of multiple dates
n/a
All examples tested working, tested various other date formats being parsed with and without passing a date format parameter
n/a
> Implementation of `unixTimestamp` Replace Variable

- src/gui/app/directives/controls/searchableEventDropdown.js
- src/gui/app/directives/filters/filterList.js
- src/gui/app/directives/modals/events/addOrEditEventModal.js
- src/gui/js/plugins/select.js
updates the add edit events for aria so that each field has context 
#2617
used NVDA to verify that each element is named proper
> feat: add aria for missing fields in addeditevents

- src/backend/variables/builtin/misc/unix-timestamp.ts
Turns out Numbers are in fact Numbers, oops 😰
n/a
No functionality changes, but did confirm it still works just in case
n/a
> Fixed `possibleDataOutput` for `unixTimestamp` Replacement Variable

- src/gui/app/directives/modals/events/simulateGroupEventsModal.js
Co-authored-by: DennisRijsdijk <dennisrijsdijk@users.noreply.github.com>
some scripts would try to use null as a manualMetadata 
resulting in error 
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'type')
at simulateGroupEventsModal.js:101:71
at Array.map (<anonymous>)
at $ctrl.eventChanged (simulateGroupEventsModal.js:97:82)
```
this change trys to help alleviate that but will fail with nulled type objects 
as illustrated in this screenshot campaign info is empty
and to be clear i do not have tiltify configured so that may change 
#2647
this was loaded with the tiltafy script and tested as its the only offended script that could be found
> Fix: manual metadata null values for strings

- src/backend/variables/builtin/twitch/chat/message/chat-message-text-only.ts
Addresses a couple of rough edges in `$chatMessageTextOnly`:
- Adds command trigger removal by default.
- Adds examples showing what the variable can do.
- Better defensive programming used throughout.
- Better trims white space everywhere it touches (but not within text parts that include it!)
- Unicode emoji will still get through. This only removes: twitch emotes, third-party emotes, cheermotes, and URLs.
- Added commentary to describe things, and esoteric scenarios that may come up.
N/A
*Yes*. CKY will still likely have an esoteric regex trigger that could behave unexpectedly, however.
N/A
> fix: $chatMessageTextOnly Wash, Wax, and Polish

- src/backend/variables/builtin/array/array-element.ts
- src/backend/variables/builtin/array/array-remove.ts
- `$arrayRemove`
- Add "first" option as an index argument, with examples.
- Shortcut single-item arrays into returning [].
- `$arrayElement`
- Add numerous invocation examples.
- Add "first" and "last" as index arguments.
- POSSIBLY BREAKING: use Array.isArray to validate that it's an array.
- This likely *BREAKS* ArrayBuffer, Uin8Array, DataView, Blob, etc. types.
N/A
Tested a command using the following in a **Log Message**, which all output appropriate text, g-i being null:
```
a) $arrayElement["[1,2,3]", 0]
b) $arrayElement["[1,2,3]", first]
c) $arrayElement["[1,2,3]", last]
d) $arrayRemove["[1,2,3]", 0]
e) $arrayRemove["[1,2,3]", first]
f) $arrayRemove["[1,2,3]", last]
g) $arrayElement["[1,2,3]", 4]
h) $arrayElement["[1,2,3]", four]
i) $arrayElement["[1,2,3]", -1]
j) …
```
> feat: $array indexing improvements

- src/server/websocket-server-manager.ts
Fixes a startup error related to the websocket server manager's reportClientsToFrontend
Ensured the error no longer shows up on startup.
> fix: startup error in reportClientsToFrontend

- src/gui/app/directives/modals/viewers/viewerDetailsModal.js
Fixes an issue in the viewer card where a mismatch between the userDB username and Twitch username caused metadata to not save.
#2658
Ensured that user metadata properly saves and deletes for users with matching usernames
Ensured that user metadata properly saves and deletes for users with mismatched usernames
> fix: user metadata not saving when username mismatch

- src/gui/app/directives/modals/variables/add-or-edit-variable-macro-modal.js
Changes Enter key behavior on name and description fields to save instead of opening a new modal instance
Ensured the modal now saves and closes rather than opening a new modal instance
> fix: don't open new macro modal when pressing enter on input

- package-lock.json
- package.json
- src/backend/effects/builtin-effect-loader.js
- src/backend/effects/builtin/activity-feed-alert.ts
- src/backend/events/activity-feed-manager.js
- src/gui/app/services/activity-feed.service.js
- src/gui/app/templates/chat/_chat-messages.html
this effect adds the ability to create entries in the activity feed.  
this change Required UUID Types so that was added in the package it is working but not sure if version 10.0.0 is too new? 
im unsure if the package lock is needed. 
#2634
added effect to preset list and changed the icon added text then clicked play 
added effect to preset list left icon empty and added text then clicked play as noted in the screenshots
> feat (effect): add activity feed effect

- src/backend/effects/builtin/cooldown-command.js
- Cooldown effect search bar isn't ideal when the search text starts with an exclamation mark.
- Thanks angular.
- [I'm not the only one](https://github.com/crowbartools/Firebot/pull/2643/commits/f9ef09bf97b9fd88db5bb74a50bff26ed7d06952)!
**Before**:
**After**:
> fix: (effect) Cooldown Search Negation

- src/gui/app/directives/modals/setups/create-setup-modal.js
Adds the .firebotsetup file extension to a setup created on Linux
#2677 
Ensured setups on linux now save with file extension
Ensured setups save properly with one instance of the file extension on Windows and Mac
> fix: export setup file extension on linux (#2677)

- src/gui/app/directives/modals/channel-rewards/add-edit-channel-reward.js
Fixed an issue where channel rewards can generate invalid color codes, causing reward save/creation to fail silently
#2680
Ensured short color codes are now padded with 0s until the color code is valid
> fix: channel rewards creating invalid default color codes

- src/gui/app/directives/controls/sort-tags-row.js
- Edits the tags popover menus to include add or add/edit tags menu options.
- The padding and margin values look appropriate for me, but are open to be adjusted as desired.
#2188 
Yes.
Screenshot of an empty component lacking tags, atop a separate screenshot of a component with several tags available (manually blurred out for screenshot purposes):
> feat: Add add/edit tags to sort-tags-row components

- src/backend/variables/builtin/utility/index.ts
- src/backend/variables/builtin/utility/random-uuid.ts
adds a randomUUID variable with the intent that it be used on http requests and html ids
among any other place a uuid is required. 
fixed missing ; in the index.ts while i was there.. 
#2693
ran chat command with uuid as the string output.
> feat: (variable) randomUUID

- src/backend/chat/chat-listeners/twitch-chat-listeners.js
- src/backend/events/builtin/twitch-event-source.js
- src/backend/events/twitch-events/announcement.ts
- src/backend/events/twitch-events/chat-message.ts
- src/backend/events/twitch-events/viewer-arrived.ts
- src/backend/variables/builtin/twitch/chat/message/chat-message-id.ts
- src/backend/variables/builtin/twitch/chat/message/chat-message.ts
- src/backend/variables/builtin/twitch/chat/message/index.ts
Adds Chat Message Deleted event and $chatMessageId to commands and chat message related events
#2687 
Ensured commands, chat event and new chat message deleted event properly supply $chatMessageId
Ensured chat message deleted event properly supplies $chatMessage, $user, $userDisplayName and $userId variables
> feat: chat message deleted event

- src/backend/variables/builtin/metadata/effect-output.ts
Add property path and default data to effectOutput, similar to customVariable
#2091
Ensured providing no property path still returns the full value
Ensured providing a property path to an object or array output results in the proper path or defaultData being returned
Ensured providing a null property path to use defaultData returns defaultData when there is no data
Ensured using a JSON stringified effect output (eg. Obs Raw Request) returns the proper data at the property path
> feat: enable propertyPath and defaultData for effectOutput

- src/backend/integrations/builtin/obs/effects/set-obs-color-source-color.ts
- src/gui/app/directives/controls/color-picker-input.js
fixed an issue where RGB-only color codes in the OBS Color Source Effect didn't get padded for transparency, thus getting transparency: 0 from OBS
Added a color picker for OBS Color Source Effect that allows users to pick a color with alpha
Added a custom color mode that allows for replace variables that result in ARGB hex codes
partially resolves #2250
- Variables are now allowed in the custom mode, however `$obsColorValue` will invert the color as it was meant for raw requests. #2076 may provide a solution here.
Ensured pre-existing effects (saved as ARGB) show their appropriate color, both with and without saving from effect settings UI
Ensured pre-existing effects switch to Custom Color mode when entering effect settings UI
Ensured new effects start in color picker mode with a default …
> feat: OBS Color Picker, Raw/Variable Color Entry

- src/gui/app/directives/modals/chat/add-or-edit-custom-quick-action-modal.js
- src/gui/app/directives/modals/counters/add-edit-counter-modal.js
- src/gui/app/directives/modals/effect-queues/addOrEditEffectQueueModal.js
- src/gui/app/directives/modals/effects/add-edit-preset-effect-list-modal.js
Removes id generation in the frontend for quick actions, counters, queues and preset lists so JsonDbManager sends out the proper event.
Ensured quick actions, counters, queues and preset lists save properly
Ensured creating a quick action, counter, queue or preset list emits the `created-item` event rather than `updated-item`
> fix: JsonDbManager created-item event

- src/server/websocket-server-manager.ts
Fixes passing the instanceName into the overlay-connected event
#2742
Ensured $overlayInstance now reflects the instance that caused the event
> fix: overlay instance name for overlay connected event

- src/backend/integrations/builtin/obs/obs-remote.ts
- Fix a bug where the OBS Program Scene Changed event was firing twice.
- Fix a bug where OBS Transition Started event could not access the new $obsSceneName until after a Scene Changed event propagates once the scene transition fully completes.
- This is likely a bug or oversight in OBS Websockets.
- But it can be worked around by immediately querying for the new scene name once a Transition Started event is received.
#2749
> fix: OBS Scene Transition/Change Fixups

- src/gui/app/directives/effect-option-settings/eosOverlayRotation.js
fix rotation field text box height 
#2761
made sure the element was not a fixed height when seizing the textbox
> fix: remove rotation height

- src/backend/variables/builtin/misc/active-chat-user-count.ts
- Adds `$activeChatUserCount[customRole]` for filtering the count of active chat users by the custom role.
- Changed some `require`-syntax imports to actual `import`-syntax.
#2750
Verified operational with several groups with three differing accounts over various activity states.
> feat (vars): Add Custom Role filtering to $activeChatUserCount

- src/backend/variables/builtin/array/array-slice.ts
- src/backend/variables/builtin/array/index.ts
Adds an `arraySlice` replace variable that lets users easily get a truncated version of an array, also fixed a typo
#2775 
Tested the variable with various starts/ends including positive integers, negative integers, decimals, invalid strings, empty strings and undefined, including not including either start or end, and just including start
n/a
> Feat: `arraySlice` replace variable

- src/backend/events/EventManager.js
complex manualMetadata eg:
manualMetadata: {
title: "Poll name"
choices: {
type: "choice-list",
value:[
{ id: "c0113c14-144e-475c-9647-a65f9177665d", title: "Test Choice 1" },
{ id: "6d86797a-d88a-4fc2-b4f6-1895afdc503e", title: "Test Choice 2" },
{ id: "791bc06c-c4d5-4c74-b950-8596c04dbb0d", title: "Test Choice 3" }
]
}
}
being malformed on test event button
this would cause variable data to return the variable name. 
#2783 
made many events that leverage Enum and arbitrary data structs to see what the variable data would return in the console log  
1000 Test message
Firebot,User1, User2, User3, User4, User5,
[{"id":"c0113c14-144e-475c-9647-a65f9177665d","index":1,"title":"Test Choice 1","points":62,"votes":125},{"id":"6d86797a-d88a-4fc2-b4f6-1895afdc503e","index":2,"title":"Test Choice …
> fix(events): complex manualMetadata being malformed on test event button

- src/backend/effects/builtin/clips.js
- src/backend/effects/builtin/play-video.js
move clips to use twitchs iFrame.
#2768
tested clip playback in the overlay.
clips will now be gated by CCL [ContentDisplayPreferences](https://help.twitch.tv/s/article/how-to-customize-content?language=en_US#ContentDisplayPreferences)
if streamers would like the gated video to play they will need to interact in the browser object and allow it for the first time. obs then "should" save the choice as a cookie object. 
this is out of our control and we do not receive the CCL in the clip endpont data. 
this will not be affected by the https://www.twitch.tv/settings/content-preferences that is unless the browser source is logged in  to twitch in the browser source.
> fix: Move clips to iframe

- src/backend/quick-actions/quick-action-manager.js
Changes the quickActionManager to return the quick action on save, rather than `true | undefined`
#2507
Ensured quick actions save properly and no longer error into console
> fix: frontend error when saving quick action

- src/backend/effects/queues/effect-queue-runner.js
- src/backend/events/builtin/firebot-event-source.js
- src/backend/events/filters/builtin-filter-loader.js
- src/backend/events/filters/builtin/effect-queue.js
- src/backend/variables/builtin/metadata/effect-queue-name.ts
- src/backend/variables/builtin/metadata/effect-queue-status.ts
- src/backend/variables/builtin/metadata/index.ts
- Added `Effect Queue Status` as event that trigger when the status of a queue changes. 
- Added `Effect Queue Added` as a event that triggers when a new item are added to a effect queue.
- Added a filter for  `Effect Queue Status` , `Effect Queue Added` and existing `Effect Queue Cleared`.
- Added new `effectQueueStatus` ReplaceVariable that returns the `true` or `false` or `null` based of the status of the effect queue.
None
- Setup test queue and Chat alert messages to see if it logs correctly
- Filter tested the same way and working
- Filters:
- Variables:
- Add new event
> feat: add more events to Effect Queue

- src/backend/events/builtin/twitch-event-source.js
- src/backend/events/filters/builtin/raid-viewer-count.js
- src/backend/events/twitch-events/raid.ts
- src/backend/twitch-api/eventsub/eventsub-client.ts
- src/backend/variables/builtin/twitch/index.ts
- src/backend/variables/builtin/twitch/raid/index.ts
- src/backend/variables/builtin/twitch/raid/raid-target-user-display-name.ts
- src/backend/variables/builtin/twitch/raid/raid-target-user-id.ts
- src/backend/variables/builtin/twitch/raid/raid-target-username.ts
- src/backend/variables/builtin/twitch/raid/raid-viewer-count.ts
- src/gui/app/services/settings.service.js
Added Raid Sent off event to the event list. 
Created accompanying variable changes and activity feed changes 
#2767 
Manual:
Raid Sent Off:
1. Add Event for Raid Sent Off 
2. Raid a given channel 
3. Once raid is completed effects are fired off and message appears in activity feed
Regression:
Incoming raid
1. Add Event for Incoming Raid
2. Receive a Raid from a different channel
3. Once raid is completed effects are fired off and message appears in activity feed
activity feed
Event Names
Filter Hint Message
> Feature Request #2767 Raid Sent Off Event

- src/gui/app/controllers/chat-messages.controller.js
- src/gui/app/services/chat-messages.service.js
- src/gui/app/services/settings.service.js
- src/gui/app/templates/chat/_chat-messages.html
- Caches the active chat sender, outgoing chat message text, and reply/thread information in the dashboard when the chat-messages controller gets reloaded.
- This intentionally **does not** get saved to disk, and the application will always start back up with "Streamer" as the active chat sender.
- Does not add any actual settings, checkboxes, nor UI. It just remembers the thing you already changed while the application stays active.
- Previously, changing component tabs then changing back would cause the chat sender to get reset to Streamer, the message text to be blank, and the reply-to/thread information to be dropped. This was *not* cool.
#2353
Yup, video evidence of functionality:
[![Video Of Tests](https://github.com/user-attachments/assets/919dc509-61cd-4b98-9901-55ce343ad0de)](http …
> feat: Remember Active Dashboard Chat User, Message Text, and Replying-To

- src/backend/variables/builtin/user/roles/has-role.ts
- src/backend/variables/builtin/user/roles/has-roles.ts
Fixes usage examples for `$hasRoles` and adds examples for `$hasRole`.
- Role name comparisons are case-sensitive.
- Moderator and VIP being the actual names from Twitch.
- So reflect those accurately in the examples.
- ... and clear up a few lint warnings (white space, ignored params)
Discord #questions thread: [give VIP or Mod role based on metadata?](https://discord.com/channels/372817064034959370/1281786252558991490)
Minimal
> fix: $hasRole and $hasRoles Usage Examples

- src/backend/common/handlers/createClipProcessor.js
try to fix clips streamer not live issue  
by removing the api call 
we need this to be in a nightly to have an affected user test it. 
I am unsure if the clip can even be created because of the twitch bugged processing if a user is broadcasting and erroring
> fix: clip live check

- src/backend/effects/builtin/cooldown-command.js
- src/backend/effects/builtin/toggle-command.ts
- src/backend/effects/builtin/toggle-scheduled-task.ts
- src/backend/effects/builtin/toggle-timer.ts
- src/backend/effects/builtin/update-channel-reward.ts
Update Toggle-by-tag and cooldown-by-tag functionality to handle possible missing sort tags
#2787
#2861 
Ensured toggle-by tag and cooldown-by tag for commands, channel rewards, timers and scheduled effect lists properly ignore any items that are missing the sortTags property
> fix: toggle-by-tag throwing error if sortTags prop is missing

- src/backend/chat/moderation/chat-moderation-manager.js
- src/backend/chat/moderation/url-permit-command.ts
Update the behavior of the !permit command to support case-insensitive input and display names
#2862
Ensured case-insensitive usernames and displaynames work
Ensured displaynames that are different from the username work
> fix: case sensitivity in !permit moderation command

- src/gui/app/directives/chat/feed items/chat-message.js
remove the width of ffz and 7tv emotes so they display proper
2842
#2842
> fix: ffz and 7tv wide emotes overlap

- src/backend/app-management/electron/window-management.js
When `--fbuser-data-directory=/path/to/dataFolder` is passed into Firebot, the backend correctly uses this directory. However, the frontend doesn't. Because of this, some things like the profile selector use data from appdata, while the backend uses the specified data path. 
This PR passes the `fbuser-data-folder` parameter into the MainWindow to ensure both frontend and backend are always working on the same data folder.
Ensured the profiles overview shows the profiles for the specified data folder, rather than the appdata folder.
> fix: frontend reading incorrect data folder

- src/backend/effects/builtin/activity-feed-alert.ts
Move the variable menu on the "Activity Feed Alert" effect to the bottom position to mitigate any top-clipping
#2833
Ensured the variables menu does not clip visually
> fix: menu position for activity feed effect

- src/server/api/v1/controllers/customRolesApiController.ts
- src/server/api/v1/v1Router.js
Adds an API route `/customRoles/:customRoleId/clear` that allows removing all viewers from the custom role
#2483
Ensured endpoint does proper error checking for role existing, and properly clears role of all viewers
> feat: clear custom role api

- src/backend/variables/builtin/user/roles/custom-role-users.ts
`$customRoleUsers` is hard-coded to return user display names for back-compat reasons. This PR adds a property path selector parameter to the `$customRoleUsers` variable to allow for selecting:
- `username` to get the raw usernames, capable of being utilized with `$userMetadata` or for any other purpose.
- `raw` to get raw viewer objects: { `id`: string, `username`: string, `displayName`: string }.
`raw` selectors provides zero immediate benefits to my eye, but *might* be useful someday to someone. You're welcome hypothetical person reading this later. 😆
Additionally, changed the example description for the default usage example to highlight that it yields display names, instead of usernames.
N/A. Made an untested decision in my Phasmophobia guessing game custom setup, and am trying to …
> feat (vars): Add $customRoleUsers Property Selector Parameter

- src/gui/scss/core/_controls.scss
> The start of my CSS arc...
- Expanded sort tags in Light theme were previously #25292a on #808080 which is rather jarring, and somewhat difficult to read.
- Changed them to be #25292a on #d3d3d3 to match the Add Tag button and the collapsed tags button.
- Obsidian and Midnight themes remain entirely unchanged by this.
N/A
Verified to the best of my abilities that there were zero side effects of this outside of the intended expanded tags background change.
> css: Light Theme Sort Tags Contrast

- .vscode/launch.json
updates the render debug timeout to be 90 seconds instead of 30
makes sure the debugging can connect, 
Firebots source is on a plater drive for me and sometimes takes just a little longer to connect to the render debug
> chore: launch timeout

- src/gui/scss/Light.scss
- src/gui/scss/Midnight.scss
- src/gui/scss/Obsidian.scss
the chat alert was WAY to bright and hard to read. 
reducing the alpha of the color while maintaining the color helped with the brightness
> chore: tone down the brightness of the chat alert bg color

- src/backend/chat/moderation/chat-moderation-manager.js
fixes 
```
[2024-10-11 05:39:51.0843] - error: [v5.63.2] Unhandled promise rejection 
{
message: "Cannot read properties of null (reading 'minutesInChannel')",
stack: "TypeError: Cannot read properties of null (reading 'minutesInChannel')\n" +
'    at Object.moderateMessage (C:\\Users\\bradt\\AppData\\Local\\firebot\\app-5.63.2\\resources\\app.asar\\build\\backend\\chat\\moderation\\chat-moderation-manager.js:199:51)\n' +
'    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
'    at async C:\\Users\\bradt\\AppData\\Local\\firebot\\app-5.63.2\\resources\\app.asar\\build\\backend\\chat\\chat-listeners\\twitch-chat-listeners.js:37:9'
}
```
this only corrects the view time part of this error. 
there is another aspect that i am still trying to figure out
part …
> fix: url chat Moderation view time

- src/backend/common/handlers/fileWriterProcessor.js
remove trailing carriage return in write to file effect for replace line by text where there is an unexpected "\r" on some files. 
#2891
loaded a file with 
```
54 65 73 74 20 41 72 67 75 6D 65 6E 74 3A 20 33 0D 0A 
54 65 73 74 20 41 72 67 75 6D 65 6E 74 3A 20 31 0D 0A
54 65 73 74 20 41 72 67 75 6D 65 6E 74 3A 20 32 0D 0A
54 65 73 74 20 41 72 67 75 6D 65 6E 74 3A 20 39 0D 0A 
54 65 73 74 20 41 72 67 75 6D 65 6E 74 3A 20 34 0D 0A
```
```
Test Argument: 3
Test Argument: 1
Test Argument: 2
Test Argument: 5
Test Argument: 4
```
replaced Test Argument: 5  with Test Argument: 9
```
54 65 73 74 20 41 72 67 75 6D 65 6E 74 3A 20 33 0A
54 65 73 74 20 41 72 67 75 6D 65 6E 74 3A 20 31 0A 
54 65 73 74 20 41 72 67 75 6D 65 6E 74 3A 20 32 0A 
54 65 73 74 20 41 72 67 75 6D 65 6E 74 3A 20 39 0A 
54 65 73 …
```
> fix: remove carriage return in write to file effect

- src/backend/variables/builtin/user/user-display-name.ts
- src/backend/variables/builtin/user/user-id.ts
- Add argument-less examples to both of the `$userId` and `$userDisplayName` variables, and list them first.
- Break everything about these variables by defaulting to `metadata.eventData...` and falling back to `metadata...`. -Dennis
#2903
"Yes"
> feat: Add Some Arg-Less Examples for $user... Variables

- src/server/api/v1/controllers/variableApiController.js
- src/server/api/v1/v1Router.js
added an api endpoint for registered variables 
#2898
http://localhost:7472/api/v1/variables returns an alphabetised array of all variables
> feat: built in variable api

- src/backend/variables/builtin/counter/counter.ts
- src/backend/variables/builtin/currency/currency-rank.ts
- src/backend/variables/builtin/currency/currency.ts
- src/backend/variables/builtin/metadata/index.ts
- src/backend/variables/builtin/number/math.ts
- src/backend/variables/builtin/number/number-commafy.ts
- src/backend/variables/builtin/number/number-floor.ts
- src/backend/variables/builtin/number/number-max.ts
- src/backend/variables/builtin/number/number-min.ts
- src/backend/variables/builtin/text/text-capitalize.ts
- src/backend/variables/builtin/text/text-decode-from-url.ts
- src/backend/variables/builtin/twitch/index.ts
- src/backend/variables/builtin/user/index.ts
- src/backend/variables/builtin/utility/index.ts
- src/backend/variables/builtin/utility/video-duration.ts
Update some replace variable examples that were incorrectly changed in #2908
> chore: replace variable examples

- src/backend/utility.js
fixes typo in filters to to prevent the entire name from being an array
> fix: split typo in filters

- src/gui/app/directives/controls/sound-player.js
- src/gui/app/index.html
- src/gui/app/services/sound.service.js
Replace core usage of Howler with native `HTMLAudioElement` class. Keeping dependency as it's currently being passed to scripts.
No logged issue, but may address intermittent issues with sounds played via the app (i.e. not via overlay).
Validated maintained existing functionality: sounds played on both default & specific devices and also stopped early when requested.
N/A
> fix: stop using Howler

- src/backend/effects/builtin/text-to-speech.ts
- src/gui/app/directives/settings/categories/tts-settings.js
- src/gui/app/services/tts.service.js
- Convert the system Text-to-Speech effect from JS to TS.
- Add a `boolean | undefined` "wait" property to its effect model, and UI for it.
- `true`: the speech synthesis is await-able.
- Enables the effect to mostly work properly in Firebot effect queues.
- ...excepting queue priorities: SpeechSynthesis API appears to lack insert or reorder functionality.
- But it *will* wait until after the speech has played out, or been cancelled mid-sentence/removed from the queue by a "Clear Effects" effect.
- `false | undefined`: current behavior.
- Add a `boolean` "wait" param to the TTS service `readText()` function, and `await` when `true`.
- ~~Add a "read-tts-async" communicator event that behaves much like "read-tts" but await-able.~~
- Lean into the async.
- Convert "read-tts" communicator …
> feat: Awaitable System TTS

- src/gui/app/directives/conditional-effect/conditionDisplay.js
Adding a conditional effect then clearing the text of the condition used to display "[Not Set]" for the condition. This was changed, at some point in time (I'll leave it up to you to track down *when* this change occurred), and the conditions now appear as empty space, at least since Firebot v.5.63.2.
This PR changes it back to how it used to be, and instead displays "[Not Set]" again for empty conditions.
#2985 
Thoroughly tested with numerous condition types and values. Only formerly empty display values appear to have been changed, which is a promising sight.
Before:
After:
> fix: Empty Conditional Effects Showing Empty Conditions

- src/gui/app/services/notification.service.js
Changes the notification manager service's "update" toast to use the ngToast className of "warning" instead of "warn".
#2997
None.
N/A.
> fix: Update Notification className

- src/backend/variables/builtin/utility/index.ts
- src/backend/variables/builtin/utility/overlay-resources-path.ts
add a variable to get the system path of the overlay-resources path
allow traversal of array of paths to be used in play video, play sound, show image and obs;s path effects.
#2988
$overlayResourcesPath/audio/ding.wav
$overlayResourcesPath[audio, ding.wav]
$overlayResourcesPath[audio/ding.wav]
slash oriantiation dont matter on windows but could be affected on other systems 
both return 
"C:\Users\cky\AppData\Roaming\Firebot\v5\overlay-resources\audio/ding.wav"
path.resolve is um dumb and allows you to go where you should not 
$overlayResourcesPath[/etc/passwd]
n
> feat(variables): Overlay-Resources folder variable. (#2988)

- src/backend/effects/builtin/toggle-event.js
- src/gui/app/directives/controls/firebot-select.js
- Loading a dropdown-select element with no values available to bind to it previously locked it into string-handling mode.
- This broke the Toggle Event effect on initial creation, which expected object-handling mode, but supplied no initial binding values.
- As such, the initially saved effect data used the name of the event, instead of the unique ID of it.
- Added an optional one-way "value-mode" attribute to dropdown-select to force it to operate in either object or string mode, or default to prior behavior when unspecified.
- Fixed two arrow-parens.
- Beyond original scope:
- Have the effect's group name track renaming of event sets, which would cause similar problems in the effect's UI.
#3006
Tested Toggle Event creation and editing thoroughly, plus a handful of others. I still need …
> fix: Toggle Event Effect Chooser Data Typing

- src/gui/app/directives/settings/categories/advanced-settings.js
pesky typo removed an extra s 
we dont have a function called `settings.getSettings`
#3011
opened the settings menu
> fix(settings): PersistCustomVariables advanced settings show selection

- src/backend/font-manager.ts
- src/gui/app/controllers/chat-messages.controller.js
- src/gui/app/directives/chat/feed items/chat-message.js
- src/gui/app/directives/modals/chat/chat-settings-modal.js
- src/gui/app/templates/chat/_chat-messages.html
- src/types/settings.ts
- Add a Use Custom Font toggle to chat settings. This expands to reveal a searching ui-select font chooser for chat message text.
- This custom font is used for message text, and not URLs, alerts, usernames, or in any other areas besides message and replying-to text.
- The ui-select-choices displays the font name, an emdash, and the stylized font name in *that* font face, in the custom size when enabled.
- Added two settings:
- `ChatCustomFontFamily` string, with the name of the font to use.
- `ChatCustomFontFamilyEnabled` boolean, whether or not to use a custom font face.
- The 12 default fonts are included in the available list, and more can be added through the Overlay Settings.
- Without more ancillary work in font manager, there's no way to choose font-style for the default fonts, …
> feat(chat UI): Custom Chat Message Fonts (#2955)

- src/backend/events/EventManager.js
- src/backend/events/events-router.js
- src/gui/app/directives/modals/events/simulateGroupEventsModal.js
- Revert #1889
- Removes the "Force event to run" checkbox in the Simulate Event modal.
- Disable event caching for simulated events.
- This impacts only simulation of: follow, raid, reward redemption, and viewer arrived event types. Nothing else was using the event cache (in core).
#2672
#1782
~~Minimal (it works), but I need to submit this first and rouse some troops together for more depth and breadth of testing.~~
Live events and simulated events behave appropriately. Follow/unfollow/follow (and raid) spam hits the caching layer (one event gets through per 12 hrs), before and/or after a simulation with the same data.
New (old) simulate dialog:
Log of simulating two raids from the same user in quick succession:
> fix(events): Don't Cache Simulated Events (#2672)

- src/backend/chat/chat-listeners/active-user-handler.js
- src/backend/variables/builtin/user/random-active-viewer.ts
- Accept either a single custom role name or an array of multiple custom role names for inclusion filtering..
- Accept either a single user name or an array of multiple user names for exclusion filtering.
- Add a parameter to exclude a single custom role name or an array of custom role names.
- Add a parameter to return either or both the username and/or id.
- `displayName` is unavailable here though, sadly.
- Good thing there's a variable available for that. 😁
- Uses `$arrayFrom[..., ...]` for one readable example of array parameters.
- Which also shows that `$streamer` and `$bot`  should probably always be added to the ignored users filter.
- Squashed an historic bug in `activeUserHandler.getAllActiveUsers` that was returning user ids as `number` instead of `string`.
#2805
Tested quite …
> feat(vars): $randomActiveViewer Enhancements (#2805)

- package-lock.json
- package.json
- src/backend/variables/builtin/array/array-fuzzy-search.ts
- src/backend/variables/builtin/array/index.ts
Introduced an `arrayFuzzySearch` variable that allows a user to find the closest match in an array for a provided search
#3002 
Tested all 3 provided examples to ensure they work as expected, and also tested passing in a simple custom variable array and an array from an HTTP Request response
n/a
> feat(variables): added `arrayFuzzySearch` variable (#3002)

- src/backend/events/filters/builtin/twitch/gift-count.ts
- src/backend/events/filters/builtin/twitch/sub-type.ts
Restore the 'is not' comparison for the sub tier event filter
Restore the gift count filter event ID
#3060
#3064
Ensured both the 'is' and 'is not' comparisons function as expected by simulating the "Sub" event and going through all tiers
> fix: regressions in filter rework (#3060) (#3064)

- src/backend/common/effect-runner.js
- Propagate effect errors by rejecting them.
- Previous behavior broke queues anytime an effect excepted inside of one without a duration specified.
#3066 
"yes" -#firebot-experts
> fix(queue): Effect Errors Shouldn't Break Queues (#3066)

- src/gui/app/directives/chat/feed items/chat-message.js
- src/gui/scss/core/_chat.scss
- Twitch revised certain global emotes to be rectangular.
- This broke our fixed-width CSS for it, causing emotes to overlap text.
#3069 
Tested with numerous emotes around packed text.
Twitch web chat view:
Firebot (condensed) view:
> fix(ui): Emote Overlaps Text (#3069)

- src/backend/chat/chat-helpers.ts
- Parens are added in the [frontend](<https://github.com/crowbartools/Firebot/blob/8ccad4702fdcb4766262d95325149dd9a20f9d9c/src/gui/app/directives/chat/feed%20items/chat-message.js#L203>), there's no need to duplicate them here.
- This shouldn't actually be seen, but ~~if~~ *when* something breaks, it'll look a smidge better.
- "Move fast and break things" can unfortunately result in some broken things.
N/A
> chore: De-duplicate Parens for Malformed AutoMod Reasons

- src/backend/variables/builtin/array/array-slice.ts
A ternary operator in the renderer for `$arraySlice` was returning falsey when 0 was passed in as a parameter and causing incorrect outputs as a result, this simply fixes the method to properly check for empty strings.
#3078 
Tested with `0` in both "start" and "end" fields of `$arraySlice`, as well as checking other values to ensure no regressions
> fix(variables): `$arraySlice` "end" parameter can misinterpret the number `0` (#3078)

- src/gui/app/directives/conditional-effect/conditionDisplay.js
- Condition values of literal zero no longer show `[Not Set]` in the overview.
- This was overlooked in #2986, but existed prior to it.
#3086
Tested numerous ways to potentially break it, some with absolutely atrocious conditions, and all appeared fine.
> fix(effects): Condition of 0 was displaying as [Not Set] (#3086)

- src/gui/app/index.html
Add back the ability to choose custom colors in Summernote (Show Text effect).
- The top-left frame placement is not ideal.
- The lack of alpha transparency is not ideal.
- But custom colors are better than none?
#3100
Selected several colors (insert a *skittles.png* meme here).
> fix(summernote): Restore Ability to Select Custom Colors (#3100)

- src/gui/app/directives/effect-option-settings/eosAudioOutputDevice.js
- src/gui/app/directives/settings/categories/general-settings.js
- src/gui/app/services/sound.service.js
This Pull Request adds a centralized `audioService.getOutputDevices` and switches all prior usages of `navigator.mediaDevices.enumerateDevices()` to use it instead. This function filters out the `default`, `communication` and any non-`audiooutput` devices, as the `eosAudioOutputDevice` already did.
#3105 
Ensured play-sound still works on regular audio devices
Ensured play-sound now works on virtual audio cables
Ensured derivative effect (Amazon Polly TTS) still play audio to regular audio devices
Ensured derivative effect (Amazon Polly TTS) plays audio to virtual audio cable
Ensured Settings > Sound Output Device shows the list of proper audio devices.
> fix(audio): playback on virtual audio cables (#3105)

- src/gui/app/controllers/effect-queues.controller.js
- src/gui/app/directives/modals/effect-queues/addOrEditEffectQueueModal.js
- src/gui/app/services/effect-queues.service.js
- Update default type for new Effect Queues to Sequential
- Resize addOrEditEffectQueueModal to medium size
- switch to firebot-radio-cards for Queue Mode
#3110
Ensured the default selected queue mode is now Sequential
Ensured opening/editing an existing queue does not change its queue mode
Ensured Sequential, Custom and Interval queues can all be created properly
Ensured queues still display properly in the item-table
Ensured queues still function as expected
> feat: switch default queue type to Sequential (#3110)

- src/backend/events/filters/builtin/twitch/chat-mode.ts
- src/backend/events/filters/builtin/twitch/sub-kind.ts
- src/backend/events/filters/filter-factory.ts
- src/gui/app/directives/filters/filterDisplay.js
Inject presetValues into the getSelectedValueDisplay function for event filters
#3083
Ensured both in-tree filters and plugin filters can access presetValues
Tested some builtin preset type filters to ensure they display the correct values
>  feat: inject presetValues into getSelectedValueDisplay (#3083) 

- src/gui/app/index.html
- src/gui/scss/core/_global.scss
- Summernote 0.8.20 has styling issues when toggling the code view twice, 0.8.19 has css issues where the buttons icons are missing.
- 0.8.16 resolved the custom color issue from #3104, but has table transparency issues.
- 0.8.18 is 0.8.17 but with better translations (that we'll never see)
- So settle with 0.8.18 which seems to be fully functional, and free of glaringly-obvious bugs, and as many non-obvious ones that I could think to check for.
- Add readable default foreground coloring regardless of background color, and soften the contrast a smidge.
- The somewhat violates the ideals of a WYSIWYG editor, but we were *already* doing that by not specifying a default theme.
- At least now it's usable regardless of the background color mode.
#3131
Before (0.8.20):
After (0.8.18): …
> fix(UI): Revert Summernote Back To 0.8.18 To Fix Style Issues (#3131)

- src/backend/variables/builtin/twitch/subs/index.ts
- src/backend/variables/builtin/twitch/subs/is-anonymous.ts
- Add an `$isAnonymous` variable.
- We already had an event filter for this, but a variable unlocks more functionality such as conditional effects and inline `$if[$isAnonymous, ...]`-style evaluation.
- Limited solely to community/subs-gifted events, as cheering anonymously was removed circa October 2022, [for safety](<https://fixvx.com/TwitchSupport/status/1585408826257416192>).
#3127
Simulated and manually ran both impacted events thoroughly (community-subs-gifted, subs-gifted).
N/A
> feat(vars): Add $isAnonymous Variable (#3127)

- src/backend/effects/builtin/play-video.js
- src/backend/effects/builtin/shoutout.js
- src/backend/effects/builtin/show-image.js
- src/backend/effects/builtin/show-text.js
- src/gui/app/directives/effect-option-settings/eosOverlayPosition.js
add z-index to position control and apply it to the 4 overlay effects 
shoutout 
play video 
show image 
show text 
#1789
showed an image behind video over top of text
> feat(overlay): add z-index to postion of overlay(#1789)

- src/backend/effects/builtin/play-video.js
show the volume slider when experimental clips is enabled 
#3129
checked that the settings both enabling and disabling the slider was working for clips in experimental mode
> feat(effects): Add the Volume Slider Back for experimental clips (#3129)

- src/backend/effects/builtin-effect-loader.js
- src/backend/effects/builtin/twitch/shield-mode.ts
This PR adds an effect that can enable and disable "shield mode" for the broadcaster's channel.
This is supported by Twurple so this is just the typical firebot wrappers around:
```javascript
await twitchApi.streamerClient.moderation.updateShieldModeStatus(streamerUserId, activate);
```
Fixes https://github.com/crowbartools/Firebot/issues/3160
Ran the preset effect list shown in the screen shots and shield mode was enabled and then disabled in the channel.
Result in my Twitch stream from running the above preset effect list:
> feat(effects): Add "shield mode" effect (#3160)

- src/gui/app/directives/misc/firebot-item-table/firebot-item-table.html
- src/gui/app/directives/misc/firebot-item-table/firebot-item-table.js
- firebot-item-table: fixes undefined error on init when no sort-tag-context is passed. This is done by changing the ID to a random UUID instead. The reason for picking a random UUID is that I have an edge case where I need 2 item-tables on the same page, so I need the IDs to be unique
- firebot-item-table: hides sort tag dropdown when no sort-tag-context is passed
#3148
Ensured via script dev that the error no longer appears and the sort tag dropdown is no longer there.
Ensured app-included firebot-item-table usages still work as expected
> fix: firebot-item-table without sort-tag-context (#3148)

- src/backend/effects/builtin/chat-feed-alert.js
- src/gui/app/directives/chat/feed items/chat-alert.js
- src/gui/app/services/chat-messages.service.js
- src/gui/app/templates/chat/_chat-messages.html
This makes the icon displayed in the chat feed for the "Chat Feed Alert" effect configurable.
It uses the standard icon picker, and defaults to the old value (`fad fa-exclamation-circle`) when unspecified. (The icon picker widget always displays the little flag and not the actual selected icon, but that's the way it works on all the screens.)
The same code that powers the "Chat Feed Alert" command is also called under-the-hood for certain actions, such as clearing the chat. This now defaults to `fad fa-exclamation-circle`.
So in short this is now selectable when someone edits an existing "Chat Feed Alert" effect or creates a new one, and keeps the default behavior at all other times.
Fixes https://github.com/crowbartools/Firebot/issues/3157
Made a preset effect list that had a "Chat Feed …
> feat(effects): Make chat feed alert icon configurable (#3157)

- src/backend/variables/builtin/text/atob.ts
- src/backend/variables/builtin/text/base64-decode.ts
- src/backend/variables/builtin/text/base64-encode.ts
- src/backend/variables/builtin/text/btoa.ts
- src/backend/variables/builtin/text/index.ts
This PR adds two new base64 related variables: `$base64Encode` and `$base64Decode`, and two new variables that alias those: `$btoa` and `$atob` respectively.
Note: The implementation here should work properly with emojis or other multi-byte Unicode characters as well (tested this).
Note: The original issue (which I wrote) had these as `base64encode` and `base64decode`, but looking at the other variables in that directory, they seem to use camelCase, so I did too.
Fixes https://github.com/crowbartools/Firebot/issues/3186
Tested this in a chat feed alert. See screenshot.
This is in the log:
```
[2025-06-19 06:32:11.0701] - error: Failed to decode base64 string: !
```
> feat: Add base64 encode and decode variables (#3186)

- src/gui/app/directives/controls/effectList.js
Fixes a bug introduced in #3253 which always disabled the edit effect button in the context menu
#3287
Ensured edit effect is properly enabled for effects that exist, and disabled for effects that don't
> fix: edit effect always disabled (#3287)
